[tool.poetry]
name = "requify"
version = "0.1.0"
description = "Автоматизированная система управления требованиями"
authors = ["Eugene <e.krotov03@gmail.com>"]
readme = "README.md"
packages = [{include = "requify"}]

[tool.poetry.dependencies]
python = "^3.13"
fastapi = {extras = ["all"], version = "^0.115.12"}
sqlalchemy = "^2.0.41"
black = "^25.1.0"
asyncpg = "^0.30.0"
uvicorn = "^0.34.2"
pydantic-settings = "^2.9.1"
psycopg2-binary = "^2.9.10"
python-dotenv = "^1.1.0"
alembic = "^1.13.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-asyncio = "^0.24.0"
pytest-cov = "^6.0.0"
httpx = "^0.28.0"
isort = "^5.13.0"
flake8 = "^7.0.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
