"""init

Revision ID: 8c1d246bdff6
Revises:
Create Date: 2025-07-31 00:31:28.957899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c1d246bdff6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False, comment="Название компании"),
        sa.Column(
            "slug", sa.String(length=100), nullable=False, comment="URL-friendly идентификатор"
        ),
        sa.Column(
            "legal_name", sa.String(length=300), nullable=True, comment="Юридическое название"
        ),
        sa.Column(
            "description",
            sa.String(length=1000),
            nullable=True,
            comment="Краткое описание компании",
        ),
        sa.Column(
            "type",
            sa.Enum(
                "STARTUP",
                "SMALL_BUSINESS",
                "MEDIUM_BUSINESS",
                "ENTERPRISE",
                "NON_PROFIT",
                "GOVERNMENT",
                "EDUCATIONAL",
                name="companytype",
            ),
            nullable=False,
            comment="Тип компании",
        ),
        sa.Column("industry", sa.String(length=100), nullable=True, comment="Отрасль"),
        sa.Column(
            "size_category",
            sa.String(length=50),
            nullable=True,
            comment="Категория размера (micro, small, medium, large)",
        ),
        sa.Column("employee_count", sa.Integer(), nullable=True, comment="Количество сотрудников"),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUSPENDED", "INACTIVE", "TRIAL", "ARCHIVED", name="companystatus"),
            nullable=False,
            comment="Статус компании",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активна ли компания"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("slug", name=op.f("uq_companies_slug")),
    )
    op.create_index("ix_companies_is_active", "companies", ["is_active"], unique=False)
    op.create_index("ix_companies_legal_name", "companies", ["legal_name"], unique=False)
    op.create_index("ix_companies_slug", "companies", ["slug"], unique=True)
    op.create_index("ix_companies_status", "companies", ["status"], unique=False)
    op.create_index("ix_companies_type", "companies", ["type"], unique=False)
    op.create_table(
        "enhanced_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Название роли"),
        sa.Column(
            "display_name",
            sa.String(length=200),
            nullable=False,
            comment="Отображаемое название роли",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание роли и обязанностей"),
        sa.Column("scope", sa.String(length=20), nullable=False, comment="Область действия роли"),
        sa.Column(
            "role_level",
            sa.Integer(),
            nullable=False,
            comment="Уровень роли (0=базовый, 10=высший)",
        ),
        sa.Column("system_role", sa.String(length=50), nullable=True, comment="Системная роль"),
        sa.Column("company_role", sa.String(length=50), nullable=True, comment="Роль в компании"),
        sa.Column(
            "department_role", sa.String(length=50), nullable=True, comment="Роль в департаменте"
        ),
        sa.Column("team_role", sa.String(length=50), nullable=True, comment="Роль в команде"),
        sa.Column("project_role", sa.String(length=50), nullable=True, comment="Роль в проекте"),
        sa.Column("is_system", sa.Boolean(), nullable=False, comment="Системная ли роль"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активна ли роль"),
        sa.Column("is_default", sa.Boolean(), nullable=False, comment="Роль по умолчанию"),
        sa.Column("is_assignable", sa.Boolean(), nullable=False, comment="Можно ли назначать роль"),
        sa.Column(
            "requires_approval",
            sa.Boolean(),
            nullable=False,
            comment="Требует одобрения для назначения",
        ),
        sa.Column(
            "priority", sa.Integer(), nullable=False, comment="Приоритет роли (выше = важнее)"
        ),
        sa.Column(
            "max_assignees",
            sa.Integer(),
            nullable=True,
            comment="Максимальное количество носителей роли",
        ),
        sa.Column(
            "permissions_config", sa.JSON(), nullable=True, comment="Конфигурация разрешений (JSON)"
        ),
        sa.Column("restrictions", sa.JSON(), nullable=True, comment="Ограничения роли (JSON)"),
        sa.Column(
            "role_metadata", sa.JSON(), nullable=True, comment="Дополнительные метаданные роли"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enhanced_roles")),
    )
    op.create_index("ix_enhanced_roles_is_active", "enhanced_roles", ["is_active"], unique=False)
    op.create_index("ix_enhanced_roles_is_system", "enhanced_roles", ["is_system"], unique=False)
    op.create_index("ix_enhanced_roles_name", "enhanced_roles", ["name"], unique=False)
    op.create_index("ix_enhanced_roles_role_level", "enhanced_roles", ["role_level"], unique=False)
    op.create_index("ix_enhanced_roles_scope", "enhanced_roles", ["scope"], unique=False)
    op.create_table(
        "relationship_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship_types")),
        sa.UniqueConstraint("name", name=op.f("uq_relationship_types_name")),
    )
    op.create_table(
        "requirement_priorities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_priorities")),
        sa.UniqueConstraint("name", name=op.f("uq_requirement_priorities_name")),
    )
    op.create_table(
        "requirement_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("workflow_transitions", sa.ARRAY(sa.Integer()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_statuses")),
        sa.UniqueConstraint("name", name=op.f("uq_requirement_statuses_name")),
    )
    op.create_table(
        "requirement_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_types")),
        sa.UniqueConstraint("name", name=op.f("uq_requirement_types_name")),
    )
    op.create_table(
        "company_branding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False, comment="ID компании"),
        sa.Column(
            "logo_url", sa.String(length=500), nullable=True, comment="URL основного логотипа"
        ),
        sa.Column(
            "logo_dark_url",
            sa.String(length=500),
            nullable=True,
            comment="URL логотипа для темной темы",
        ),
        sa.Column(
            "logo_light_url",
            sa.String(length=500),
            nullable=True,
            comment="URL логотипа для светлой темы",
        ),
        sa.Column("favicon_url", sa.String(length=500), nullable=True, comment="URL favicon"),
        sa.Column(
            "banner_url", sa.String(length=500), nullable=True, comment="URL баннера компании"
        ),
        sa.Column(
            "background_url",
            sa.String(length=500),
            nullable=True,
            comment="URL фонового изображения",
        ),
        sa.Column(
            "watermark_url", sa.String(length=500), nullable=True, comment="URL водяного знака"
        ),
        sa.Column(
            "primary_color",
            sa.String(length=7),
            nullable=True,
            comment="Основной цвет (hex, например #007bff)",
        ),
        sa.Column(
            "secondary_color",
            sa.String(length=7),
            nullable=True,
            comment="Дополнительный цвет (hex)",
        ),
        sa.Column(
            "accent_color", sa.String(length=7), nullable=True, comment="Акцентный цвет (hex)"
        ),
        sa.Column(
            "background_color", sa.String(length=7), nullable=True, comment="Цвет фона (hex)"
        ),
        sa.Column(
            "surface_color", sa.String(length=7), nullable=True, comment="Цвет поверхности (hex)"
        ),
        sa.Column(
            "text_color", sa.String(length=7), nullable=True, comment="Основной цвет текста (hex)"
        ),
        sa.Column(
            "text_secondary_color",
            sa.String(length=7),
            nullable=True,
            comment="Дополнительный цвет текста (hex)",
        ),
        sa.Column("success_color", sa.String(length=7), nullable=True, comment="Цвет успеха (hex)"),
        sa.Column(
            "warning_color", sa.String(length=7), nullable=True, comment="Цвет предупреждения (hex)"
        ),
        sa.Column("error_color", sa.String(length=7), nullable=True, comment="Цвет ошибки (hex)"),
        sa.Column(
            "info_color", sa.String(length=7), nullable=True, comment="Информационный цвет (hex)"
        ),
        sa.Column(
            "primary_font_family",
            sa.String(length=200),
            nullable=True,
            comment="Основное семейство шрифтов",
        ),
        sa.Column(
            "secondary_font_family",
            sa.String(length=200),
            nullable=True,
            comment="Дополнительное семейство шрифтов",
        ),
        sa.Column(
            "monospace_font_family",
            sa.String(length=200),
            nullable=True,
            comment="Моноширинный шрифт",
        ),
        sa.Column(
            "font_size_base", sa.String(length=10), nullable=True, comment="Базовый размер шрифта"
        ),
        sa.Column(
            "font_size_small", sa.String(length=10), nullable=True, comment="Малый размер шрифта"
        ),
        sa.Column(
            "font_size_large", sa.String(length=10), nullable=True, comment="Большой размер шрифта"
        ),
        sa.Column("h1_font_size", sa.String(length=10), nullable=True, comment="Размер шрифта H1"),
        sa.Column("h2_font_size", sa.String(length=10), nullable=True, comment="Размер шрифта H2"),
        sa.Column("h3_font_size", sa.String(length=10), nullable=True, comment="Размер шрифта H3"),
        sa.Column(
            "button_border_radius",
            sa.String(length=10),
            nullable=True,
            comment="Радиус границ кнопок",
        ),
        sa.Column("button_padding", sa.String(length=20), nullable=True, comment="Отступы кнопок"),
        sa.Column(
            "card_border_radius",
            sa.String(length=10),
            nullable=True,
            comment="Радиус границ карточек",
        ),
        sa.Column("card_shadow", sa.String(length=50), nullable=True, comment="Тень карточек"),
        sa.Column(
            "input_border_radius",
            sa.String(length=10),
            nullable=True,
            comment="Радиус границ полей ввода",
        ),
        sa.Column(
            "input_border_color",
            sa.String(length=7),
            nullable=True,
            comment="Цвет границ полей ввода",
        ),
        sa.Column(
            "theme_name",
            sa.String(length=50),
            nullable=False,
            comment="Название темы (default, dark, light, custom)",
        ),
        sa.Column("is_dark_theme", sa.Boolean(), nullable=False, comment="Темная ли тема"),
        sa.Column("custom_css", sa.Text(), nullable=True, comment="Кастомные CSS стили"),
        sa.Column("custom_js", sa.Text(), nullable=True, comment="Кастомный JavaScript код"),
        sa.Column(
            "layout_type",
            sa.String(length=20),
            nullable=False,
            comment="Тип макета (full_width, boxed, fluid)",
        ),
        sa.Column("sidebar_width", sa.String(length=10), nullable=True, comment="Ширина сайдбара"),
        sa.Column("header_height", sa.String(length=10), nullable=True, comment="Высота заголовка"),
        sa.Column("enable_animations", sa.Boolean(), nullable=False, comment="Включить анимации"),
        sa.Column(
            "animation_duration",
            sa.String(length=10),
            nullable=True,
            comment="Длительность анимаций",
        ),
        sa.Column(
            "company_slogan", sa.String(length=200), nullable=True, comment="Слоган компании"
        ),
        sa.Column("brand_description", sa.Text(), nullable=True, comment="Описание бренда"),
        sa.Column(
            "social_links", sa.JSON(), nullable=True, comment="Ссылки на социальные сети (JSON)"
        ),
        sa.Column(
            "product_name",
            sa.String(length=100),
            nullable=True,
            comment="Кастомное название продукта",
        ),
        sa.Column(
            "login_page_title",
            sa.String(length=100),
            nullable=True,
            comment="Заголовок страницы входа",
        ),
        sa.Column(
            "dashboard_title", sa.String(length=100), nullable=True, comment="Заголовок дашборда"
        ),
        sa.Column("hide_powered_by", sa.Boolean(), nullable=False, comment="Скрыть 'Powered by'"),
        sa.Column(
            "hide_help_links", sa.Boolean(), nullable=False, comment="Скрыть ссылки на помощь"
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активна ли схема брендинга"),
        sa.Column("is_default", sa.Boolean(), nullable=False, comment="Схема по умолчанию"),
        sa.Column(
            "version", sa.String(length=10), nullable=False, comment="Версия схемы брендинга"
        ),
        sa.Column(
            "advanced_settings",
            sa.JSON(),
            nullable=True,
            comment="Дополнительные настройки брендинга (JSON)",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_branding_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_branding")),
    )
    op.create_index(
        "ix_company_branding_company_id", "company_branding", ["company_id"], unique=False
    )
    op.create_index(
        "ix_company_branding_is_active", "company_branding", ["is_active"], unique=False
    )
    op.create_index(
        "ix_company_branding_theme_name", "company_branding", ["theme_name"], unique=False
    )
    op.create_table(
        "company_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False, comment="ID компании"),
        sa.Column(
            "contact_type",
            sa.String(length=50),
            nullable=False,
            comment="Тип контакта (main, branch, billing, support, legal)",
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False, comment="Основной контакт компании"),
        sa.Column(
            "label",
            sa.String(length=100),
            nullable=True,
            comment="Название контакта (Головной офис, Филиал в Москве и т.д.)",
        ),
        sa.Column("email", sa.String(length=100), nullable=True, comment="Основной email"),
        sa.Column("support_email", sa.String(length=100), nullable=True, comment="Email поддержки"),
        sa.Column(
            "billing_email", sa.String(length=100), nullable=True, comment="Email для счетов"
        ),
        sa.Column(
            "sales_email", sa.String(length=100), nullable=True, comment="Email отдела продаж"
        ),
        sa.Column("phone", sa.String(length=20), nullable=True, comment="Основной телефон"),
        sa.Column("mobile", sa.String(length=20), nullable=True, comment="Мобильный телефон"),
        sa.Column("fax", sa.String(length=20), nullable=True, comment="Факс"),
        sa.Column(
            "support_phone", sa.String(length=20), nullable=True, comment="Телефон поддержки"
        ),
        sa.Column("country", sa.String(length=100), nullable=True, comment="Страна"),
        sa.Column("region", sa.String(length=100), nullable=True, comment="Регион/область"),
        sa.Column("city", sa.String(length=100), nullable=True, comment="Город"),
        sa.Column("street_address", sa.Text(), nullable=True, comment="Адрес (улица, дом, офис)"),
        sa.Column("postal_code", sa.String(length=20), nullable=True, comment="Почтовый индекс"),
        sa.Column("building", sa.String(length=50), nullable=True, comment="Здание/корпус"),
        sa.Column("floor", sa.String(length=20), nullable=True, comment="Этаж"),
        sa.Column("office", sa.String(length=50), nullable=True, comment="Офис/кабинет"),
        sa.Column("website", sa.String(length=500), nullable=True, comment="Основной веб-сайт"),
        sa.Column("social_media", sa.Text(), nullable=True, comment="Социальные сети (JSON)"),
        sa.Column("timezone", sa.String(length=50), nullable=False, comment="Часовой пояс офиса"),
        sa.Column(
            "working_hours",
            sa.String(length=200),
            nullable=True,
            comment="Рабочие часы (пн-пт 9:00-18:00)",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_contacts_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_contacts")),
    )
    op.create_index(
        "ix_company_contacts_company_id", "company_contacts", ["company_id"], unique=False
    )
    op.create_index(
        "ix_company_contacts_contact_type", "company_contacts", ["contact_type"], unique=False
    )
    op.create_index(
        "ix_company_contacts_country_city", "company_contacts", ["country", "city"], unique=False
    )
    op.create_index(
        "ix_company_contacts_is_primary", "company_contacts", ["is_primary"], unique=False
    )
    op.create_table(
        "company_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False, comment="ID компании"),
        sa.Column(
            "domain", sa.String(length=100), nullable=True, comment="Корпоративный домен (для SSO)"
        ),
        sa.Column(
            "allow_domain_signup",
            sa.Boolean(),
            nullable=False,
            comment="Разрешить регистрацию по корпоративному домену",
        ),
        sa.Column(
            "require_email_verification",
            sa.Boolean(),
            nullable=False,
            comment="Требовать подтверждение email",
        ),
        sa.Column("enable_sso", sa.Boolean(), nullable=False, comment="Включить единый вход (SSO)"),
        sa.Column(
            "sso_provider",
            sa.String(length=50),
            nullable=True,
            comment="Провайдер SSO (google, microsoft, okta, auth0)",
        ),
        sa.Column("sso_config", sa.JSON(), nullable=True, comment="Конфигурация SSO (JSON)"),
        sa.Column(
            "enforce_2fa",
            sa.Boolean(),
            nullable=False,
            comment="Обязательная двухфакторная аутентификация",
        ),
        sa.Column("password_policy", sa.JSON(), nullable=True, comment="Политика паролей (JSON)"),
        sa.Column(
            "session_timeout_minutes",
            sa.Integer(),
            nullable=False,
            comment="Таймаут сессии в минутах (8 часов)",
        ),
        sa.Column(
            "default_language", sa.String(length=10), nullable=False, comment="Язык по умолчанию"
        ),
        sa.Column(
            "default_currency", sa.String(length=3), nullable=False, comment="Валюта по умолчанию"
        ),
        sa.Column(
            "default_timezone",
            sa.String(length=50),
            nullable=False,
            comment="Часовой пояс по умолчанию",
        ),
        sa.Column("date_format", sa.String(length=20), nullable=False, comment="Формат даты"),
        sa.Column("time_format", sa.String(length=20), nullable=False, comment="Формат времени"),
        sa.Column("number_format", sa.String(length=20), nullable=False, comment="Формат чисел"),
        sa.Column(
            "enable_email_notifications",
            sa.Boolean(),
            nullable=False,
            comment="Включить email уведомления",
        ),
        sa.Column(
            "enable_browser_notifications",
            sa.Boolean(),
            nullable=False,
            comment="Включить browser уведомления",
        ),
        sa.Column(
            "enable_slack_integration",
            sa.Boolean(),
            nullable=False,
            comment="Включить интеграцию со Slack",
        ),
        sa.Column(
            "notification_settings",
            sa.JSON(),
            nullable=True,
            comment="Настройки уведомлений (JSON)",
        ),
        sa.Column(
            "allowed_integrations",
            sa.JSON(),
            nullable=True,
            comment="Разрешенные интеграции (JSON)",
        ),
        sa.Column(
            "webhook_settings", sa.JSON(), nullable=True, comment="Настройки webhooks (JSON)"
        ),
        sa.Column(
            "api_rate_limit", sa.Integer(), nullable=False, comment="Лимит API запросов в час"
        ),
        sa.Column(
            "api_allowed_ips",
            sa.Text(),
            nullable=True,
            comment="Разрешенные IP для API (через запятую)",
        ),
        sa.Column(
            "require_requirement_approval",
            sa.Boolean(),
            nullable=False,
            comment="Требовать утверждение требований",
        ),
        sa.Column(
            "require_release_approval",
            sa.Boolean(),
            nullable=False,
            comment="Требовать утверждение релизов",
        ),
        sa.Column(
            "auto_assign_requirements",
            sa.Boolean(),
            nullable=False,
            comment="Автоматически назначать требования",
        ),
        sa.Column(
            "default_project_visibility",
            sa.String(length=20),
            nullable=False,
            comment="Видимость проектов по умолчанию (public, company, department, team, private)",
        ),
        sa.Column(
            "allow_external_collaborators",
            sa.Boolean(),
            nullable=False,
            comment="Разрешить внешних коллабораторов",
        ),
        sa.Column(
            "max_team_size", sa.Integer(), nullable=True, comment="Максимальный размер команды"
        ),
        sa.Column(
            "allow_cross_department_teams",
            sa.Boolean(),
            nullable=False,
            comment="Разрешить межотдельские команды",
        ),
        sa.Column("enable_analytics", sa.Boolean(), nullable=False, comment="Включить аналитику"),
        sa.Column(
            "analytics_retention_days",
            sa.Integer(),
            nullable=False,
            comment="Срок хранения аналитики (дни)",
        ),
        sa.Column(
            "enable_usage_tracking",
            sa.Boolean(),
            nullable=False,
            comment="Отслеживать использование",
        ),
        sa.Column(
            "allow_data_export", sa.Boolean(), nullable=False, comment="Разрешить экспорт данных"
        ),
        sa.Column(
            "export_formats",
            sa.String(length=200),
            nullable=False,
            comment="Разрешенные форматы экспорта",
        ),
        sa.Column(
            "custom_user_fields",
            sa.JSON(),
            nullable=True,
            comment="Кастомные поля пользователей (JSON)",
        ),
        sa.Column(
            "custom_project_fields",
            sa.JSON(),
            nullable=True,
            comment="Кастомные поля проектов (JSON)",
        ),
        sa.Column(
            "custom_requirement_fields",
            sa.JSON(),
            nullable=True,
            comment="Кастомные поля требований (JSON)",
        ),
        sa.Column("custom_labels", sa.JSON(), nullable=True, comment="Кастомные метки (JSON)"),
        sa.Column(
            "custom_workflows",
            sa.JSON(),
            nullable=True,
            comment="Кастомные рабочие процессы (JSON)",
        ),
        sa.Column(
            "file_storage_provider",
            sa.String(length=50),
            nullable=False,
            comment="Провайдер хранения файлов (local, aws_s3, google_cloud, azure)",
        ),
        sa.Column(
            "max_file_size_mb",
            sa.Integer(),
            nullable=False,
            comment="Максимальный размер файла (МБ)",
        ),
        sa.Column(
            "allowed_file_types",
            sa.String(length=500),
            nullable=False,
            comment="Разрешенные типы файлов",
        ),
        sa.Column(
            "auto_backup_enabled", sa.Boolean(), nullable=False, comment="Автоматические бэкапы"
        ),
        sa.Column(
            "backup_frequency_hours", sa.Integer(), nullable=False, comment="Частота бэкапов (часы)"
        ),
        sa.Column(
            "backup_retention_days",
            sa.Integer(),
            nullable=False,
            comment="Срок хранения бэкапов (дни)",
        ),
        sa.Column(
            "custom_settings",
            sa.JSON(),
            nullable=True,
            comment="Дополнительные кастомные настройки (JSON)",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_settings_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_settings")),
    )
    op.create_index(
        "ix_company_settings_allow_domain_signup",
        "company_settings",
        ["allow_domain_signup"],
        unique=False,
    )
    op.create_index(
        "ix_company_settings_company_id", "company_settings", ["company_id"], unique=False
    )
    op.create_index("ix_company_settings_domain", "company_settings", ["domain"], unique=False)
    op.create_index(
        "ix_company_settings_enable_sso", "company_settings", ["enable_sso"], unique=False
    )
    op.create_table(
        "company_subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False, comment="ID компании"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="Статус подписки"),
        sa.Column("plan", sa.String(length=20), nullable=False, comment="План подписки"),
        sa.Column(
            "billing_period", sa.String(length=20), nullable=False, comment="Период биллинга"
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False, comment="Дата начала подписки"),
        sa.Column("expires_at", sa.DateTime(), nullable=True, comment="Дата окончания подписки"),
        sa.Column(
            "trial_ends_at", sa.DateTime(), nullable=True, comment="Дата окончания пробного периода"
        ),
        sa.Column(
            "last_payment_at", sa.DateTime(), nullable=True, comment="Дата последнего платежа"
        ),
        sa.Column(
            "next_billing_at", sa.DateTime(), nullable=True, comment="Дата следующего списания"
        ),
        sa.Column(
            "price", sa.Numeric(precision=10, scale=2), nullable=True, comment="Цена подписки"
        ),
        sa.Column("currency", sa.String(length=3), nullable=False, comment="Валюта"),
        sa.Column(
            "discount_percent",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
            comment="Процент скидки",
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Сумма скидки",
        ),
        sa.Column(
            "total_paid",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Общая сумма оплат",
        ),
        sa.Column(
            "outstanding_amount",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Сумма задолженности",
        ),
        sa.Column(
            "max_users",
            sa.Integer(),
            nullable=True,
            comment="Максимальное количество пользователей",
        ),
        sa.Column(
            "max_projects", sa.Integer(), nullable=True, comment="Максимальное количество проектов"
        ),
        sa.Column(
            "max_departments",
            sa.Integer(),
            nullable=True,
            comment="Максимальное количество департаментов",
        ),
        sa.Column(
            "max_teams", sa.Integer(), nullable=True, comment="Максимальное количество команд"
        ),
        sa.Column(
            "max_storage_gb",
            sa.Integer(),
            nullable=True,
            comment="Максимальный объем хранилища в ГБ",
        ),
        sa.Column(
            "max_api_calls_per_month",
            sa.Integer(),
            nullable=True,
            comment="Лимит API запросов в месяц",
        ),
        sa.Column(
            "features_enabled", sa.Text(), nullable=True, comment="Включенные функции (JSON массив)"
        ),
        sa.Column(
            "integrations_allowed",
            sa.Text(),
            nullable=True,
            comment="Разрешенные интеграции (JSON массив)",
        ),
        sa.Column("custom_branding", sa.Boolean(), nullable=False, comment="Кастомный брендинг"),
        sa.Column(
            "advanced_analytics", sa.Boolean(), nullable=False, comment="Расширенная аналитика"
        ),
        sa.Column(
            "priority_support", sa.Boolean(), nullable=False, comment="Приоритетная поддержка"
        ),
        sa.Column("api_access", sa.Boolean(), nullable=False, comment="Доступ к API"),
        sa.Column("white_label", sa.Boolean(), nullable=False, comment="White label решение"),
        sa.Column(
            "billing_contact_id", sa.Integer(), nullable=True, comment="ID контакта для биллинга"
        ),
        sa.Column(
            "payment_method",
            sa.String(length=50),
            nullable=True,
            comment="Способ оплаты (card, invoice, bank_transfer)",
        ),
        sa.Column(
            "invoice_email", sa.String(length=100), nullable=True, comment="Email для счетов"
        ),
        sa.Column("auto_renew", sa.Boolean(), nullable=False, comment="Автоматическое продление"),
        sa.Column(
            "grace_period_days", sa.Integer(), nullable=False, comment="Льготный период (дни)"
        ),
        sa.Column(
            "external_subscription_id",
            sa.String(length=100),
            nullable=True,
            comment="ID в внешней платежной системе",
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="Заметки о подписке"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_subscriptions_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_subscriptions")),
    )
    op.create_index(
        "ix_company_subscriptions_company_id", "company_subscriptions", ["company_id"], unique=False
    )
    op.create_index(
        "ix_company_subscriptions_expires_at", "company_subscriptions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_company_subscriptions_plan", "company_subscriptions", ["plan"], unique=False
    )
    op.create_index(
        "ix_company_subscriptions_status", "company_subscriptions", ["status"], unique=False
    )
    op.create_index(
        "ix_company_subscriptions_trial_ends_at",
        "company_subscriptions",
        ["trial_ends_at"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=True,
            comment="Основная компания пользователя (NULL для System Admin, reference-only)",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.Column(
            "username", sa.String(length=50), nullable=False, comment="Уникальное имя пользователя"
        ),
        sa.Column(
            "email", sa.String(length=100), nullable=False, comment="Email адрес пользователя"
        ),
        sa.Column(
            "hashed_password", sa.String(length=128), nullable=False, comment="Хэшированный пароль"
        ),
        sa.Column(
            "auth0_id", sa.String(length=255), nullable=True, comment="Auth0 user ID для интеграции"
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активен ли пользователь"),
        sa.Column(
            "email_verified",
            sa.Boolean(),
            nullable=False,
            comment="Подтвержден ли email пользователя",
        ),
        sa.Column(
            "email_verified_at", sa.DateTime(), nullable=True, comment="Время подтверждения email"
        ),
        sa.Column(
            "last_login", sa.DateTime(), nullable=True, comment="Время последнего входа в систему"
        ),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name=op.f("fk_users_company_id_companies")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("auth0_id", name=op.f("uq_users_auth0_id")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index("ix_users_auth0_id_unique", "users", ["auth0_id"], unique=True)
    op.create_index("ix_users_company_id", "users", ["company_id"], unique=False)
    op.create_index("ix_users_email_unique", "users", ["email"], unique=True)
    op.create_index("ix_users_email_verified", "users", ["email_verified"], unique=False)
    op.create_index("ix_users_is_active", "users", ["is_active"], unique=False)
    op.create_index("ix_users_last_login", "users", ["last_login"], unique=False)
    op.create_index("ix_users_username_unique", "users", ["username"], unique=True)
    op.create_table(
        "dashboard_widgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("widget_type", sa.String(length=50), nullable=False),
        sa.Column("widget_title", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("size", sa.String(length=20), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_dashboard_widgets_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_widgets")),
    )
    op.create_index(op.f("ix_dashboard_widgets_id"), "dashboard_widgets", ["id"], unique=False)
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False, comment="Название департамента"),
        sa.Column(
            "slug", sa.String(length=100), nullable=False, comment="URL-friendly идентификатор"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание департамента"),
        sa.Column("company_id", sa.Integer(), nullable=False, comment="ID компании"),
        sa.Column("parent_id", sa.Integer(), nullable=True, comment="Родительский департамент"),
        sa.Column("head_id", sa.Integer(), nullable=True, comment="Руководитель департамента"),
        sa.Column("type", sa.String(length=50), nullable=False, comment="Тип департамента"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активен ли департамент"),
        sa.Column("is_billable", sa.Boolean(), nullable=False, comment="Участвует ли в биллинге"),
        sa.Column(
            "auto_assign_projects",
            sa.Boolean(),
            nullable=False,
            comment="Автоматически назначать проекты этого типа",
        ),
        sa.Column("employee_count", sa.Integer(), nullable=False, comment="Количество сотрудников"),
        sa.Column("team_count", sa.Integer(), nullable=False, comment="Количество команд"),
        sa.Column(
            "annual_budget", sa.Float(), nullable=True, comment="Годовой бюджет департамента"
        ),
        sa.Column(
            "cost_center_code", sa.String(length=50), nullable=True, comment="Код центра затрат"
        ),
        sa.Column(
            "location", sa.String(length=200), nullable=True, comment="Основное местоположение"
        ),
        sa.Column("email", sa.String(length=100), nullable=True, comment="Email департамента"),
        sa.Column("phone", sa.String(length=20), nullable=True, comment="Телефон департамента"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_departments_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["head_id"],
            ["users.id"],
            name=op.f("fk_departments_head_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["departments.id"],
            name=op.f("fk_departments_parent_id_departments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
    )
    op.create_index("ix_departments_company_id", "departments", ["company_id"], unique=False)
    op.create_index("ix_departments_head_id", "departments", ["head_id"], unique=False)
    op.create_index("ix_departments_is_active", "departments", ["is_active"], unique=False)
    op.create_index("ix_departments_parent_id", "departments", ["parent_id"], unique=False)
    op.create_index("ix_departments_slug", "departments", ["company_id", "slug"], unique=True)
    op.create_index("ix_departments_type", "departments", ["type"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "token", sa.String(length=255), nullable=False, comment="Уникальный токен обновления"
        ),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания токена"),
        sa.Column("expires_at", sa.DateTime(), nullable=False, comment="Время истечения токена"),
        sa.Column(
            "last_used_at",
            sa.DateTime(),
            nullable=True,
            comment="Время последнего использования токена",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активен ли токен"),
        sa.Column("user_agent", sa.Text(), nullable=True, comment="User-Agent клиента"),
        sa.Column("ip_address", sa.String(length=45), nullable=True, comment="IP адрес клиента"),
        sa.Column("revoked_at", sa.DateTime(), nullable=True, comment="Время отзыва токена"),
        sa.Column(
            "revoked_by", sa.String(length=50), nullable=True, comment="Причина отзыва токена"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token", name=op.f("uq_refresh_tokens_token")),
    )
    op.create_index("ix_refresh_tokens_expires_at", "refresh_tokens", ["expires_at"], unique=False)
    op.create_index("ix_refresh_tokens_is_active", "refresh_tokens", ["is_active"], unique=False)
    op.create_index("ix_refresh_tokens_token_unique", "refresh_tokens", ["token"], unique=True)
    op.create_index(
        "ix_refresh_tokens_user_active", "refresh_tokens", ["user_id", "is_active"], unique=False
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "user_dashboard_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("show_quick_stats", sa.Boolean(), nullable=True),
        sa.Column("show_recent_activity", sa.Boolean(), nullable=True),
        sa.Column("show_my_projects", sa.Boolean(), nullable=True),
        sa.Column("show_pending_approvals", sa.Boolean(), nullable=True),
        sa.Column("default_project_filter", sa.String(length=100), nullable=True),
        sa.Column("activity_limit", sa.Integer(), nullable=True),
        sa.Column("refresh_interval", sa.Integer(), nullable=True),
        sa.Column("theme", sa.String(length=20), nullable=True),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=True),
        sa.Column("email_notifications", sa.Boolean(), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("custom_settings", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_dashboard_preferences_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_dashboard_preferences")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_dashboard_preferences_user_id")),
    )
    op.create_index(
        op.f("ix_user_dashboard_preferences_id"), "user_dashboard_preferences", ["id"], unique=False
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя (1-к-1)"),
        sa.Column("first_name", sa.String(length=100), nullable=True, comment="Имя"),
        sa.Column("last_name", sa.String(length=100), nullable=True, comment="Фамилия"),
        sa.Column("middle_name", sa.String(length=100), nullable=True, comment="Отчество"),
        sa.Column("display_name", sa.String(length=200), nullable=True, comment="Отображаемое имя"),
        sa.Column("phone", sa.String(length=20), nullable=True, comment="Телефон"),
        sa.Column("phone_verified", sa.Boolean(), nullable=False, comment="Подтвержден ли телефон"),
        sa.Column("position", sa.String(length=200), nullable=True, comment="Должность"),
        sa.Column("department", sa.String(length=200), nullable=True, comment="Отдел"),
        sa.Column("employee_id", sa.String(length=50), nullable=True, comment="Табельный номер"),
        sa.Column("hire_date", sa.DateTime(), nullable=True, comment="Дата найма"),
        sa.Column("bio", sa.Text(), nullable=True, comment="О себе"),
        sa.Column("avatar_url", sa.String(length=500), nullable=True, comment="URL аватара"),
        sa.Column("timezone", sa.String(length=50), nullable=False, comment="Часовой пояс"),
        sa.Column("language", sa.String(length=10), nullable=False, comment="Язык интерфейса"),
        sa.Column("profile_completed", sa.Boolean(), nullable=False, comment="Заполнен ли профиль"),
        sa.Column(
            "profile_completion_percentage",
            sa.Integer(),
            nullable=False,
            comment="Процент заполненности профиля",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_profiles_user_id")),
    )
    op.create_index("ix_user_profiles_department", "user_profiles", ["department"], unique=False)
    op.create_index(
        "ix_user_profiles_display_name", "user_profiles", ["display_name"], unique=False
    )
    op.create_index("ix_user_profiles_position", "user_profiles", ["position"], unique=False)
    op.create_index("ix_user_profiles_user_id", "user_profiles", ["user_id"], unique=True)
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя"),
        sa.Column(
            "notification_settings",
            sa.JSON(),
            nullable=True,
            comment="Настройки уведомлений в JSON формате",
        ),
        sa.Column(
            "interface_settings",
            sa.JSON(),
            nullable=True,
            comment="Настройки интерфейса в JSON формате",
        ),
        sa.Column(
            "security_settings",
            sa.JSON(),
            nullable=True,
            comment="Настройки безопасности в JSON формате",
        ),
        sa.Column(
            "privacy_settings",
            sa.JSON(),
            nullable=True,
            comment="Настройки приватности в JSON формате",
        ),
        sa.Column("version", sa.Integer(), nullable=False, comment="Версия настроек"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_settings")),
        sa.UniqueConstraint("user_id", name=op.f("uq_user_settings_user_id")),
    )
    op.create_table(
        "user_settings_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя"),
        sa.Column(
            "settings_snapshot",
            sa.JSON(),
            nullable=False,
            comment="Снимок настроек поведения (БЕЗ профильных данных)",
        ),
        sa.Column("version", sa.Integer(), nullable=False, comment="Версия настроек"),
        sa.Column(
            "change_type",
            sa.String(length=50),
            nullable=False,
            comment="Тип изменения (create, update, import, etc.)",
        ),
        sa.Column("change_reason", sa.Text(), nullable=True, comment="Причина изменения"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_settings_history_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_settings_history")),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Название команды"),
        sa.Column("code", sa.String(length=50), nullable=False, comment="Уникальный код команды"),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание команды"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="Статус команды"),
        sa.Column("is_public", sa.Boolean(), nullable=False, comment="Публичная ли команда"),
        sa.Column(
            "max_members", sa.Integer(), nullable=True, comment="Максимальное количество участников"
        ),
        sa.Column("department_id", sa.Integer(), nullable=False, comment="ID департамента"),
        sa.Column("owner_id", sa.Integer(), nullable=False, comment="Владелец команды"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_teams_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_teams_owner_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("code", name=op.f("uq_teams_code")),
    )
    op.create_index("ix_teams_code_unique", "teams", ["code"], unique=True)
    op.create_index("ix_teams_department_id", "teams", ["department_id"], unique=False)
    op.create_index("ix_teams_name", "teams", ["name"], unique=False)
    op.create_index("ix_teams_owner_status", "teams", ["owner_id", "status"], unique=False)
    op.create_index("ix_teams_status_created", "teams", ["status", "created_at"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False, comment="Уникальный код проекта"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Название проекта"),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание проекта"),
        sa.Column("status", sa.String(length=50), nullable=False, comment="Статус проекта"),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=False,
            comment="ID компании (для партиционирования данных)",
        ),
        sa.Column(
            "department_id",
            sa.Integer(),
            nullable=False,
            comment="ID департамента (проект принадлежит департаменту)",
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False, comment="Владелец проекта"),
        sa.Column(
            "team_id",
            sa.Integer(),
            nullable=True,
            comment="Основная команда проекта (может быть NULL)",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_projects_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_projects_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_projects_owner_id_users"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_projects_team_id_teams"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("code", name=op.f("uq_projects_code")),
    )
    op.create_index("ix_projects_code_unique", "projects", ["code"], unique=True)
    op.create_index("ix_projects_company_id", "projects", ["company_id"], unique=False)
    op.create_index("ix_projects_department_id", "projects", ["department_id"], unique=False)
    op.create_index(
        "ix_projects_status_created", "projects", ["status", "created_at"], unique=False
    )
    op.create_index("ix_projects_team_id", "projects", ["team_id"], unique=False)
    op.create_table(
        "team_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False, comment="ID команды"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя"),
        sa.Column("role", sa.String(length=20), nullable=False, comment="Роль участника в команде"),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активен ли участник"),
        sa.Column(
            "joined_at", sa.DateTime(), nullable=False, comment="Время присоединения к команде"
        ),
        sa.Column("left_at", sa.DateTime(), nullable=True, comment="Время выхода из команды"),
        sa.Column(
            "title", sa.String(length=100), nullable=True, comment="Должность участника в команде"
        ),
        sa.Column("hourly_rate", sa.Float(), nullable=True, comment="Почасовая ставка участника"),
        sa.Column("notes", sa.String(length=500), nullable=True, comment="Заметки о участнике"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_members_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_team_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_members")),
    )
    op.create_index("ix_team_members_is_active", "team_members", ["is_active"], unique=False)
    op.create_index("ix_team_members_joined_at", "team_members", ["joined_at"], unique=False)
    op.create_index("ix_team_members_team_role", "team_members", ["team_id", "role"], unique=False)
    op.create_index(
        "ix_team_members_team_user", "team_members", ["team_id", "user_id"], unique=True
    )
    op.create_index("ix_team_members_user_role", "team_members", ["user_id", "role"], unique=False)
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Название релиза"),
        sa.Column("version", sa.String(length=50), nullable=False, comment="SemVer format"),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание релиза"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="Статус релиза"),
        sa.Column("planned_date", sa.DateTime(), nullable=True, comment="Планируемая дата релиза"),
        sa.Column("release_date", sa.DateTime(), nullable=True, comment="Фактическая дата релиза"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_releases_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
    )
    op.create_table(
        "requirement_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_requirement_groups_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_groups")),
    )
    op.create_table(
        "specs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание спецификации"),
        sa.Column("version", sa.String(length=50), nullable=True, comment="Версия спецификации"),
        sa.Column(
            "content", sa.JSON(), nullable=True, comment="Содержимое спецификации в JSON формате"
        ),
        sa.Column("format", sa.String(length=20), nullable=True, comment="Формат документа"),
        sa.Column("language", sa.String(length=10), nullable=True, comment="Язык спецификации"),
        sa.Column("status", sa.String(length=50), nullable=True, comment="Статус спецификации"),
        sa.Column("generated_by", sa.Integer(), nullable=True, comment="Создана пользователем"),
        sa.Column("template_id", sa.Integer(), nullable=True, comment="Шаблон спецификации"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at", sa.DateTime(), nullable=True, comment="Время последнего обновления"
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["users.id"], name=op.f("fk_specs_generated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_specs_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specs")),
    )
    op.create_table(
        "user_role_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя"),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="ID роли"),
        sa.Column(
            "company_id",
            sa.Integer(),
            nullable=True,
            comment="ID компании (NULL для системных ролей)",
        ),
        sa.Column(
            "department_id",
            sa.Integer(),
            nullable=True,
            comment="ID департамента (NULL для ролей выше департамента)",
        ),
        sa.Column(
            "team_id",
            sa.Integer(),
            nullable=True,
            comment="ID команды (NULL для ролей выше команды)",
        ),
        sa.Column(
            "project_id",
            sa.Integer(),
            nullable=True,
            comment="ID проекта (NULL для ролей выше проекта)",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активно ли назначение"),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            nullable=False,
            comment="Основная ли роль в данном контексте",
        ),
        sa.Column("starts_at", sa.DateTime(), nullable=True, comment="Дата начала действия роли"),
        sa.Column(
            "expires_at", sa.DateTime(), nullable=True, comment="Дата окончания действия роли"
        ),
        sa.Column("assigned_by", sa.Integer(), nullable=True, comment="Кем назначена роль"),
        sa.Column("approved_by", sa.Integer(), nullable=True, comment="Кем одобрена роль"),
        sa.Column("assignment_reason", sa.Text(), nullable=True, comment="Причина назначения роли"),
        sa.Column(
            "conditions", sa.JSON(), nullable=True, comment="Условия и ограничения назначения"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_user_role_assignments_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"], ["users.id"], name=op.f("fk_user_role_assignments_assigned_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_user_role_assignments_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_user_role_assignments_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_user_role_assignments_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["enhanced_roles.id"],
            name=op.f("fk_user_role_assignments_role_id_enhanced_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_user_role_assignments_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_role_assignments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_role_assignments")),
    )
    op.create_index(
        "ix_user_role_assignments_company_id", "user_role_assignments", ["company_id"], unique=False
    )
    op.create_index(
        "ix_user_role_assignments_context",
        "user_role_assignments",
        ["user_id", "company_id", "department_id", "team_id", "project_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_role_assignments_department_id",
        "user_role_assignments",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        "ix_user_role_assignments_is_active", "user_role_assignments", ["is_active"], unique=False
    )
    op.create_index(
        "ix_user_role_assignments_project_id", "user_role_assignments", ["project_id"], unique=False
    )
    op.create_index(
        "ix_user_role_assignments_role_id", "user_role_assignments", ["role_id"], unique=False
    )
    op.create_index(
        "ix_user_role_assignments_team_id", "user_role_assignments", ["team_id"], unique=False
    )
    op.create_index(
        "ix_user_role_assignments_user_id", "user_role_assignments", ["user_id"], unique=False
    )
    op.create_table(
        "requirement_group_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_data", sa.JSON(), nullable=False, comment="Снимок группы требований и связей"
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_requirement_group_versions_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["requirement_groups.id"],
            name=op.f("fk_requirement_group_versions_group_id_requirement_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_group_versions")),
    )
    op.create_table(
        "requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False, comment="Заголовок требования"),
        sa.Column("description", sa.Text(), nullable=True, comment="Подробное описание требования"),
        sa.Column(
            "deadline",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Срок выполнения требования",
        ),
        sa.Column(
            "progress",
            sa.Float(),
            nullable=False,
            comment="Прогресс выполнения требования (0.0-100.0)",
        ),
        sa.Column("type_id", sa.Integer(), nullable=False, comment="Тип требования"),
        sa.Column("priority_id", sa.Integer(), nullable=False, comment="Приоритет требования"),
        sa.Column("status_id", sa.Integer(), nullable=False, comment="Статус требования"),
        sa.Column(
            "project_id",
            sa.Integer(),
            nullable=False,
            comment="Проект, к которому относится требование",
        ),
        sa.Column("author_id", sa.Integer(), nullable=False, comment="Автор требования"),
        sa.Column(
            "last_modified_by",
            sa.Integer(),
            nullable=False,
            comment="Последний редактор требования",
        ),
        sa.Column(
            "release_id",
            sa.Integer(),
            nullable=True,
            comment="Релиз, в котором реализуется требование",
        ),
        sa.Column(
            "spec_id",
            sa.Integer(),
            nullable=True,
            comment="Спецификация, к которой относится требование",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_requirements_author_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["last_modified_by"],
            ["users.id"],
            name=op.f("fk_requirements_last_modified_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["priority_id"],
            ["requirement_priorities.id"],
            name=op.f("fk_requirements_priority_id_requirement_priorities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_requirements_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_requirements_release_id_releases"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["spec_id"],
            ["specs.id"],
            name=op.f("fk_requirements_spec_id_specs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["requirement_statuses.id"],
            name=op.f("fk_requirements_status_id_requirement_statuses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["requirement_types.id"],
            name=op.f("fk_requirements_type_id_requirement_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirements")),
    )
    op.create_index(
        "ix_requirements_author_created", "requirements", ["author_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_requirements_project_status", "requirements", ["project_id", "status_id"], unique=False
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_comments_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_comments_requirement_id_requirements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_table(
        "dashboard_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_type", sa.String(length=50), nullable=False),
        sa.Column("activity_title", sa.String(length=200), nullable=False),
        sa.Column("activity_description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("requirement_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("entity_name", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_dashboard_activities_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_dashboard_activities_requirement_id_requirements"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_dashboard_activities_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_dashboard_activities_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_activities")),
    )
    op.create_index(
        op.f("ix_dashboard_activities_id"), "dashboard_activities", ["id"], unique=False
    )
    op.create_table(
        "dashboard_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("action_url", sa.String(length=255), nullable=True),
        sa.Column("action_text", sa.String(length=100), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("requirement_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_dashboard_notifications_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_dashboard_notifications_requirement_id_requirements"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_dashboard_notifications_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_dashboard_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_notifications")),
    )
    op.create_index(
        op.f("ix_dashboard_notifications_id"), "dashboard_notifications", ["id"], unique=False
    )
    op.create_table(
        "relationships",
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["requirements.id"], name=op.f("fk_relationships_source_id_requirements")
        ),
        sa.ForeignKeyConstraint(
            ["target_id"], ["requirements.id"], name=op.f("fk_relationships_target_id_requirements")
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["relationship_types.id"],
            name=op.f("fk_relationships_type_id_relationship_types"),
        ),
        sa.PrimaryKeyConstraint("source_id", "target_id", "type_id", name=op.f("pk_relationships")),
    )
    op.create_table(
        "test_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NOT_STARTED", "IN_PROGRESS", "PASSED", "FAILED", "BLOCKED", name="teststatus"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("external_id", sa.String(length=50), nullable=True),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("tester_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_test_results_requirement_id_requirements"),
        ),
        sa.ForeignKeyConstraint(
            ["tester_id"], ["users.id"], name=op.f("fk_test_results_tester_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_results")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_results")
    op.drop_table("relationships")
    op.drop_index(op.f("ix_dashboard_notifications_id"), table_name="dashboard_notifications")
    op.drop_table("dashboard_notifications")
    op.drop_index(op.f("ix_dashboard_activities_id"), table_name="dashboard_activities")
    op.drop_table("dashboard_activities")
    op.drop_table("comments")
    op.drop_index("ix_requirements_project_status", table_name="requirements")
    op.drop_index("ix_requirements_author_created", table_name="requirements")
    op.drop_table("requirements")
    op.drop_table("requirement_group_versions")
    op.drop_index("ix_user_role_assignments_user_id", table_name="user_role_assignments")
    op.drop_index("ix_user_role_assignments_team_id", table_name="user_role_assignments")
    op.drop_index("ix_user_role_assignments_role_id", table_name="user_role_assignments")
    op.drop_index("ix_user_role_assignments_project_id", table_name="user_role_assignments")
    op.drop_index("ix_user_role_assignments_is_active", table_name="user_role_assignments")
    op.drop_index("ix_user_role_assignments_department_id", table_name="user_role_assignments")
    op.drop_index("ix_user_role_assignments_context", table_name="user_role_assignments")
    op.drop_index("ix_user_role_assignments_company_id", table_name="user_role_assignments")
    op.drop_table("user_role_assignments")
    op.drop_table("specs")
    op.drop_table("requirement_groups")
    op.drop_table("releases")
    op.drop_index("ix_team_members_user_role", table_name="team_members")
    op.drop_index("ix_team_members_team_user", table_name="team_members")
    op.drop_index("ix_team_members_team_role", table_name="team_members")
    op.drop_index("ix_team_members_joined_at", table_name="team_members")
    op.drop_index("ix_team_members_is_active", table_name="team_members")
    op.drop_table("team_members")
    op.drop_index("ix_projects_team_id", table_name="projects")
    op.drop_index("ix_projects_status_created", table_name="projects")
    op.drop_index("ix_projects_department_id", table_name="projects")
    op.drop_index("ix_projects_company_id", table_name="projects")
    op.drop_index("ix_projects_code_unique", table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_teams_status_created", table_name="teams")
    op.drop_index("ix_teams_owner_status", table_name="teams")
    op.drop_index("ix_teams_name", table_name="teams")
    op.drop_index("ix_teams_department_id", table_name="teams")
    op.drop_index("ix_teams_code_unique", table_name="teams")
    op.drop_table("teams")
    op.drop_table("user_settings_history")
    op.drop_table("user_settings")
    op.drop_index("ix_user_profiles_user_id", table_name="user_profiles")
    op.drop_index("ix_user_profiles_position", table_name="user_profiles")
    op.drop_index("ix_user_profiles_display_name", table_name="user_profiles")
    op.drop_index("ix_user_profiles_department", table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_user_dashboard_preferences_id"), table_name="user_dashboard_preferences")
    op.drop_table("user_dashboard_preferences")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_user_active", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_token_unique", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_is_active", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_expires_at", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_departments_type", table_name="departments")
    op.drop_index("ix_departments_slug", table_name="departments")
    op.drop_index("ix_departments_parent_id", table_name="departments")
    op.drop_index("ix_departments_is_active", table_name="departments")
    op.drop_index("ix_departments_head_id", table_name="departments")
    op.drop_index("ix_departments_company_id", table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_dashboard_widgets_id"), table_name="dashboard_widgets")
    op.drop_table("dashboard_widgets")
    op.drop_index("ix_users_username_unique", table_name="users")
    op.drop_index("ix_users_last_login", table_name="users")
    op.drop_index("ix_users_is_active", table_name="users")
    op.drop_index("ix_users_email_verified", table_name="users")
    op.drop_index("ix_users_email_unique", table_name="users")
    op.drop_index("ix_users_company_id", table_name="users")
    op.drop_index("ix_users_auth0_id_unique", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_company_subscriptions_trial_ends_at", table_name="company_subscriptions")
    op.drop_index("ix_company_subscriptions_status", table_name="company_subscriptions")
    op.drop_index("ix_company_subscriptions_plan", table_name="company_subscriptions")
    op.drop_index("ix_company_subscriptions_expires_at", table_name="company_subscriptions")
    op.drop_index("ix_company_subscriptions_company_id", table_name="company_subscriptions")
    op.drop_table("company_subscriptions")
    op.drop_index("ix_company_settings_enable_sso", table_name="company_settings")
    op.drop_index("ix_company_settings_domain", table_name="company_settings")
    op.drop_index("ix_company_settings_company_id", table_name="company_settings")
    op.drop_index("ix_company_settings_allow_domain_signup", table_name="company_settings")
    op.drop_table("company_settings")
    op.drop_index("ix_company_contacts_is_primary", table_name="company_contacts")
    op.drop_index("ix_company_contacts_country_city", table_name="company_contacts")
    op.drop_index("ix_company_contacts_contact_type", table_name="company_contacts")
    op.drop_index("ix_company_contacts_company_id", table_name="company_contacts")
    op.drop_table("company_contacts")
    op.drop_index("ix_company_branding_theme_name", table_name="company_branding")
    op.drop_index("ix_company_branding_is_active", table_name="company_branding")
    op.drop_index("ix_company_branding_company_id", table_name="company_branding")
    op.drop_table("company_branding")
    op.drop_table("requirement_types")
    op.drop_table("requirement_statuses")
    op.drop_table("requirement_priorities")
    op.drop_table("relationship_types")
    op.drop_index("ix_enhanced_roles_scope", table_name="enhanced_roles")
    op.drop_index("ix_enhanced_roles_role_level", table_name="enhanced_roles")
    op.drop_index("ix_enhanced_roles_name", table_name="enhanced_roles")
    op.drop_index("ix_enhanced_roles_is_system", table_name="enhanced_roles")
    op.drop_index("ix_enhanced_roles_is_active", table_name="enhanced_roles")
    op.drop_table("enhanced_roles")
    op.drop_index("ix_companies_type", table_name="companies")
    op.drop_index("ix_companies_status", table_name="companies")
    op.drop_index("ix_companies_slug", table_name="companies")
    op.drop_index("ix_companies_legal_name", table_name="companies")
    op.drop_index("ix_companies_is_active", table_name="companies")
    op.drop_table("companies")
    # ### end Alembic commands ###
