"""init

Revision ID: ac9aa8bfe450
Revises:
Create Date: 2025-08-03 00:17:53.841875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ac9aa8bfe450"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_projects_team_lead_id_users"), "projects", type_="foreignkey")
    op.drop_constraint(op.f("fk_projects_created_by_users"), "projects", type_="foreignkey")
    op.drop_constraint(op.f("fk_projects_updated_by_users"), "projects", type_="foreignkey")
    op.drop_column("projects", "team_lead_id")
    op.drop_column("projects", "end_date")
    op.drop_column("projects", "methodology")
    op.drop_column("projects", "created_by")
    op.drop_column("projects", "project_type")
    op.drop_column("projects", "priority")
    op.drop_column("projects", "is_public")
    op.drop_column("projects", "progress")
    op.drop_column("projects", "updated_by")
    op.drop_column("projects", "tags")
    op.drop_column("projects", "budget")
    op.drop_column("projects", "repository_url")
    op.drop_column("projects", "is_active")
    op.drop_column("projects", "start_date")
    op.drop_column("projects", "documentation_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "documentation_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
            comment="URL документации",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Дата начала проекта",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Активен ли проект",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "repository_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
            comment="URL репозитория",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "budget",
            sa.NUMERIC(precision=15, scale=2),
            autoincrement=False,
            nullable=True,
            comment="Бюджет проекта",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "tags",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="Теги проекта",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "updated_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Кто последний обновил проект",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "progress",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Процент выполнения проекта",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "is_public",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Публичный ли проект",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "priority",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
            comment="Приоритет проекта",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "project_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="Тип проекта",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "created_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Кто создал проект",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "methodology",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
            comment="Методология разработки",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Планируемая дата окончания проекта",
        ),
    )
    op.add_column(
        "projects",
        sa.Column(
            "team_lead_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Руководитель команды проекта",
        ),
    )
    op.create_foreign_key(
        op.f("fk_projects_updated_by_users"),
        "projects",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_projects_created_by_users"),
        "projects",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_projects_team_lead_id_users"),
        "projects",
        "users",
        ["team_lead_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
