"""add deadline to reqs

Revision ID: f22a3b34a13d
Revises: e74070c0a181
Create Date: 2025-06-30 09:24:03.383485

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f22a3b34a13d"
down_revision: Union[str, None] = "e74070c0a181"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requirements",
        sa.Column(
            "deadline",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Срок выполнения требования",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requirements", "deadline")
    # ### end Alembic commands ###
