"""Add username and mixin fields to User model nullable

Revision ID: 251985b89270
Revises: 6cf0164b538b
Create Date: 2025-08-06 19:17:49.528778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "251985b89270"
down_revision: Union[str, None] = "6cf0164b538b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="Уникальное имя пользователя",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="Уникальное имя пользователя",
    )
    # ### end Alembic commands ###
