"""addteam tables

Revision ID: 74cecc91d56f
Revises: d4c4c4e08f2b
Create Date: 2025-07-06 20:08:42.150151

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74cecc91d56f"
down_revision: Union[str, None] = "d4c4c4e08f2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="Название команды"
        ),
        sa.Column(
            "code",
            sa.String(length=50),
            nullable=False,
            comment="Уникальный код команды",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание команды"),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="Статус команды"
        ),
        sa.Column(
            "is_public", sa.Boolean(), nullable=False, comment="Публичная ли команда"
        ),
        sa.Column(
            "max_members",
            sa.Integer(),
            nullable=True,
            comment="Максимальное количество участников",
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False, comment="Владелец команды"),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Время создания записи"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_teams_owner_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("code", name=op.f("uq_teams_code")),
    )
    op.create_index("ix_teams_code_unique", "teams", ["code"], unique=True)
    op.create_index("ix_teams_name", "teams", ["name"], unique=False)
    op.create_index(
        "ix_teams_owner_status", "teams", ["owner_id", "status"], unique=False
    )
    op.create_index(
        "ix_teams_status_created", "teams", ["status", "created_at"], unique=False
    )
    op.create_table(
        "team_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False, comment="ID команды"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя"),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="Роль участника в команде",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активен ли участник"
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(),
            nullable=False,
            comment="Время присоединения к команде",
        ),
        sa.Column(
            "left_at", sa.DateTime(), nullable=True, comment="Время выхода из команды"
        ),
        sa.Column(
            "title",
            sa.String(length=100),
            nullable=True,
            comment="Должность участника в команде",
        ),
        sa.Column(
            "hourly_rate",
            sa.Float(),
            nullable=True,
            comment="Почасовая ставка участника",
        ),
        sa.Column(
            "notes", sa.String(length=500), nullable=True, comment="Заметки о участнике"
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Время создания записи"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_members_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_team_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_members")),
    )
    op.create_index(
        "ix_team_members_is_active", "team_members", ["is_active"], unique=False
    )
    op.create_index(
        "ix_team_members_joined_at", "team_members", ["joined_at"], unique=False
    )
    op.create_index(
        "ix_team_members_team_role", "team_members", ["team_id", "role"], unique=False
    )
    op.create_index(
        "ix_team_members_team_user", "team_members", ["team_id", "user_id"], unique=True
    )
    op.create_index(
        "ix_team_members_user_role", "team_members", ["user_id", "role"], unique=False
    )
    op.add_column(
        "dashboard_activities", sa.Column("team_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_dashboard_activities_team_id_teams"),
        "dashboard_activities",
        "teams",
        ["team_id"],
        ["id"],
    )
    op.add_column(
        "dashboard_notifications", sa.Column("team_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_dashboard_notifications_team_id_teams"),
        "dashboard_notifications",
        "teams",
        ["team_id"],
        ["id"],
    )
    op.add_column(
        "projects",
        sa.Column("team_id", sa.Integer(), nullable=True, comment="Команда проекта"),
    )
    op.create_foreign_key(
        op.f("fk_projects_team_id_teams"),
        "projects",
        "teams",
        ["team_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_projects_team_id_teams"), "projects", type_="foreignkey"
    )
    op.drop_column("projects", "team_id")
    op.drop_constraint(
        op.f("fk_dashboard_notifications_team_id_teams"),
        "dashboard_notifications",
        type_="foreignkey",
    )
    op.drop_column("dashboard_notifications", "team_id")
    op.drop_constraint(
        op.f("fk_dashboard_activities_team_id_teams"),
        "dashboard_activities",
        type_="foreignkey",
    )
    op.drop_column("dashboard_activities", "team_id")
    op.drop_index("ix_team_members_user_role", table_name="team_members")
    op.drop_index("ix_team_members_team_user", table_name="team_members")
    op.drop_index("ix_team_members_team_role", table_name="team_members")
    op.drop_index("ix_team_members_joined_at", table_name="team_members")
    op.drop_index("ix_team_members_is_active", table_name="team_members")
    op.drop_table("team_members")
    op.drop_index("ix_teams_status_created", table_name="teams")
    op.drop_index("ix_teams_owner_status", table_name="teams")
    op.drop_index("ix_teams_name", table_name="teams")
    op.drop_index("ix_teams_code_unique", table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
