"""Initial migration

Revision ID: 895ffd89f75f
Revises:
Create Date: 2025-06-28 10:59:34.408990

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "895ffd89f75f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False, comment="Уникальный код проекта"),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Название проекта"),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание проекта"),
        sa.Column(
            "status",
            sa.String(length=50),
            nullable=False,
            comment="Статус проекта (active, completed, archived)",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("code", name=op.f("uq_projects_code")),
    )
    op.create_index("ix_projects_code_unique", "projects", ["code"], unique=True)
    op.create_index(
        "ix_projects_status_created", "projects", ["status", "created_at"], unique=False
    )
    op.create_table(
        "relationship_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship_types")),
        sa.UniqueConstraint("name", name=op.f("uq_relationship_types_name")),
    )
    op.create_table(
        "requirement_priorities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_priorities")),
        sa.UniqueConstraint("name", name=op.f("uq_requirement_priorities_name")),
    )
    op.create_table(
        "requirement_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_statuses")),
        sa.UniqueConstraint("name", name=op.f("uq_requirement_statuses_name")),
    )
    op.create_table(
        "requirement_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_types")),
        sa.UniqueConstraint("name", name=op.f("uq_requirement_types_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "username", sa.String(length=50), nullable=False, comment="Уникальное имя пользователя"
        ),
        sa.Column(
            "email", sa.String(length=100), nullable=False, comment="Email адрес пользователя"
        ),
        sa.Column(
            "hashed_password", sa.String(length=128), nullable=False, comment="Хэшированный пароль"
        ),
        sa.Column("name", sa.String(length=100), nullable=True, comment="Полное имя пользователя"),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="Роль пользователя (admin, manager, analyst, developer, tester, user)",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активен ли пользователь"),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            nullable=False,
            comment="Является ли пользователь суперпользователем",
        ),
        sa.Column(
            "last_login", sa.DateTime(), nullable=True, comment="Время последнего входа в систему"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index("ix_users_email_unique", "users", ["email"], unique=True)
    op.create_index("ix_users_is_active", "users", ["is_active"], unique=False)
    op.create_index("ix_users_last_login", "users", ["last_login"], unique=False)
    op.create_index("ix_users_role_created", "users", ["role", "created_at"], unique=False)
    op.create_index("ix_users_username_unique", "users", ["username"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "token", sa.String(length=255), nullable=False, comment="Уникальный токен обновления"
        ),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя"),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания токена"),
        sa.Column("expires_at", sa.DateTime(), nullable=False, comment="Время истечения токена"),
        sa.Column(
            "last_used_at",
            sa.DateTime(),
            nullable=True,
            comment="Время последнего использования токена",
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False, comment="Активен ли токен"),
        sa.Column("user_agent", sa.Text(), nullable=True, comment="User-Agent клиента"),
        sa.Column("ip_address", sa.String(length=45), nullable=True, comment="IP адрес клиента"),
        sa.Column("revoked_at", sa.DateTime(), nullable=True, comment="Время отзыва токена"),
        sa.Column(
            "revoked_by", sa.String(length=50), nullable=True, comment="Причина отзыва токена"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token", name=op.f("uq_refresh_tokens_token")),
    )
    op.create_index("ix_refresh_tokens_expires_at", "refresh_tokens", ["expires_at"], unique=False)
    op.create_index("ix_refresh_tokens_is_active", "refresh_tokens", ["is_active"], unique=False)
    op.create_index("ix_refresh_tokens_token_unique", "refresh_tokens", ["token"], unique=True)
    op.create_index(
        "ix_refresh_tokens_user_active", "refresh_tokens", ["user_id", "is_active"], unique=False
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False)
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Название релиза"),
        sa.Column("version", sa.String(length=50), nullable=False, comment="SemVer format"),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание релиза"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="Статус релиза"),
        sa.Column("planned_date", sa.DateTime(), nullable=True, comment="Планируемая дата релиза"),
        sa.Column("release_date", sa.DateTime(), nullable=True, comment="Фактическая дата релиза"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_releases_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
    )
    op.create_table(
        "requirement_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_requirement_groups_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_groups")),
    )
    op.create_table(
        "specs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=True, comment="Шаблон спецификации"),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_specs_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specs")),
    )
    op.create_table(
        "requirement_group_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_data", sa.JSON(), nullable=False, comment="Снимок группы требований и связей"
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_requirement_group_versions_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["requirement_groups.id"],
            name=op.f("fk_requirement_group_versions_group_id_requirement_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_group_versions")),
    )
    op.create_table(
        "requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False, comment="Заголовок требования"),
        sa.Column("description", sa.Text(), nullable=True, comment="Подробное описание требования"),
        sa.Column("type_id", sa.Integer(), nullable=False, comment="Тип требования"),
        sa.Column("priority_id", sa.Integer(), nullable=False, comment="Приоритет требования"),
        sa.Column("status_id", sa.Integer(), nullable=False, comment="Статус требования"),
        sa.Column(
            "project_id",
            sa.Integer(),
            nullable=False,
            comment="Проект, к которому относится требование",
        ),
        sa.Column("author_id", sa.Integer(), nullable=False, comment="Автор требования"),
        sa.Column(
            "last_modified_by",
            sa.Integer(),
            nullable=False,
            comment="Последний редактор требования",
        ),
        sa.Column(
            "release_id",
            sa.Integer(),
            nullable=True,
            comment="Релиз, в котором реализуется требование",
        ),
        sa.Column(
            "spec_id",
            sa.Integer(),
            nullable=True,
            comment="Спецификация, к которой относится требование",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False, comment="Время создания записи"),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_requirements_author_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["last_modified_by"],
            ["users.id"],
            name=op.f("fk_requirements_last_modified_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["priority_id"],
            ["requirement_priorities.id"],
            name=op.f("fk_requirements_priority_id_requirement_priorities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_requirements_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_requirements_release_id_releases"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["spec_id"],
            ["specs.id"],
            name=op.f("fk_requirements_spec_id_specs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["requirement_statuses.id"],
            name=op.f("fk_requirements_status_id_requirement_statuses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["requirement_types.id"],
            name=op.f("fk_requirements_type_id_requirement_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirements")),
    )
    op.create_index(
        "ix_requirements_author_created", "requirements", ["author_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_requirements_project_status", "requirements", ["project_id", "status_id"], unique=False
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_comments_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_comments_requirement_id_requirements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_table(
        "relationships",
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["requirements.id"], name=op.f("fk_relationships_source_id_requirements")
        ),
        sa.ForeignKeyConstraint(
            ["target_id"], ["requirements.id"], name=op.f("fk_relationships_target_id_requirements")
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["relationship_types.id"],
            name=op.f("fk_relationships_type_id_relationship_types"),
        ),
        sa.PrimaryKeyConstraint("source_id", "target_id", "type_id", name=op.f("pk_relationships")),
    )
    op.create_table(
        "test_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NOT_STARTED", "IN_PROGRESS", "PASSED", "FAILED", "BLOCKED", name="teststatus"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("external_id", sa.String(length=50), nullable=True),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("tester_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_test_results_requirement_id_requirements"),
        ),
        sa.ForeignKeyConstraint(
            ["tester_id"], ["users.id"], name=op.f("fk_test_results_tester_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_results")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_results")
    op.drop_table("relationships")
    op.drop_table("comments")
    op.drop_index("ix_requirements_project_status", table_name="requirements")
    op.drop_index("ix_requirements_author_created", table_name="requirements")
    op.drop_table("requirements")
    op.drop_table("requirement_group_versions")
    op.drop_table("specs")
    op.drop_table("requirement_groups")
    op.drop_table("releases")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_user_active", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_token_unique", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_is_active", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_expires_at", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("ix_users_username_unique", table_name="users")
    op.drop_index("ix_users_role_created", table_name="users")
    op.drop_index("ix_users_last_login", table_name="users")
    op.drop_index("ix_users_is_active", table_name="users")
    op.drop_index("ix_users_email_unique", table_name="users")
    op.drop_table("users")
    op.drop_table("requirement_types")
    op.drop_table("requirement_statuses")
    op.drop_table("requirement_priorities")
    op.drop_table("relationship_types")
    op.drop_index("ix_projects_status_created", table_name="projects")
    op.drop_index("ix_projects_code_unique", table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
