"""extend_specs_table_for_generation

Revision ID: dd1ce4f76107
Revises: f22a3b34a13d
Create Date: 2025-06-30 10:48:17.497566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd1ce4f76107"
down_revision: Union[str, None] = "f22a3b34a13d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to specs table for enhanced specification generation
    op.add_column('specs', sa.Column(
        'description', 
        sa.Text(), 
        nullable=True, 
        comment="Описание спецификации"
    ))
    op.add_column('specs', sa.Column(
        'version', 
        sa.String(length=50), 
        nullable=True, 
        server_default='1.0',
        comment="Версия спецификации"
    ))
    op.add_column('specs', sa.Column(
        'content', 
        sa.JSON(), 
        nullable=True, 
        comment="Содержимое спецификации в JSON формате"
    ))
    op.add_column('specs', sa.Column(
        'format', 
        sa.String(length=20), 
        nullable=True, 
        server_default='pdf',
        comment="Формат документа"
    ))
    op.add_column('specs', sa.Column(
        'language', 
        sa.String(length=10), 
        nullable=True, 
        server_default='ru',
        comment="Язык спецификации"
    ))
    op.add_column('specs', sa.Column(
        'status', 
        sa.String(length=50), 
        nullable=True, 
        server_default='draft',
        comment="Статус спецификации"
    ))
    op.add_column('specs', sa.Column(
        'generated_by', 
        sa.Integer(), 
        nullable=True, 
        comment="Создана пользователем"
    ))
    op.add_column('specs', sa.Column(
        'updated_at', 
        sa.DateTime(), 
        nullable=True, 
        server_default=sa.text('CURRENT_TIMESTAMP'),
        comment="Время последнего обновления"
    ))
    
    # Add foreign key constraint for generated_by
    op.create_foreign_key(
        op.f('fk_specs_generated_by_users'),
        'specs', 
        'users', 
        ['generated_by'], 
        ['id']
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove foreign key constraint
    op.drop_constraint(op.f('fk_specs_generated_by_users'), 'specs', type_='foreignkey')
    
    # Remove added columns
    op.drop_column('specs', 'updated_at')
    op.drop_column('specs', 'generated_by')
    op.drop_column('specs', 'status')
    op.drop_column('specs', 'language')
    op.drop_column('specs', 'format')
    op.drop_column('specs', 'content')
    op.drop_column('specs', 'version')
    op.drop_column('specs', 'description')
    
    # ### end Alembic commands ###
