"""

Revision ID: fd1c524c6d82
Revises: a6568ede6ad2
Create Date: 2025-06-28 16:47:47.681211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd1c524c6d82"
down_revision: Union[str, None] = "a6568ede6ad2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("first_name", sa.String(length=100), nullable=True, comment="Имя пользователя"),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_name", sa.String(length=100), nullable=True, comment="Фамилия пользователя"
        ),
    )
    op.add_column(
        "users",
        sa.Column("department", sa.String(length=100), nullable=True, comment="Отдел пользователя"),
    )
    op.add_column(
        "users",
        sa.Column("phone", sa.String(length=20), nullable=True, comment="Телефон пользователя"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone")
    op.drop_column("users", "department")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
