"""Add_email_verification_fields

Revision ID: ed81715576d0
Revises: fd1c524c6d82
Create Date: 2025-06-28 17:47:44.133427

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed81715576d0"
down_revision: Union[str, None] = "fd1c524c6d82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_verified",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
            comment="Подтвержден ли email пользователя",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_verified_at", sa.DateTime(), nullable=True, comment="Время подтверждения email"
        ),
    )
    op.create_index("ix_users_email_verified", "users", ["email_verified"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_email_verified", table_name="users")
    op.drop_column("users", "email_verified_at")
    op.drop_column("users", "email_verified")
    # ### end Alembic commands ###
