"""add_progress_to_requirements

Revision ID: d4c4c4e08f2b
Revises: 76bab077d1d1
Create Date: 2025-07-05 19:22:49.921708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4c4c4e08f2b"
down_revision: Union[str, None] = "76bab077d1d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем поле как nullable сначала
    op.add_column(
        "requirements",
        sa.Column(
            "progress",
            sa.Float(),
            nullable=True,
            comment="Прогресс выполнения требования (0.0-100.0)",
        ),
    )

    # Устанавливаем значение по умолчанию для существующих записей
    op.execute("UPDATE requirements SET progress = 0.0 WHERE progress IS NULL")

    # Теперь делаем поле NOT NULL
    op.alter_column("requirements", "progress", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("requirements", "progress")
    # ### end Alembic commands ###
