"""add json to spec table

Revision ID: fcaa4255dc19
Revises: dd1ce4f76107
Create Date: 2025-06-30 10:51:30.875116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fcaa4255dc19"
down_revision: Union[str, None] = "dd1ce4f76107"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specs", sa.Column("description", sa.Text(), nullable=True, comment="Описание спецификации")
    )
    op.add_column(
        "specs",
        sa.Column("version", sa.String(length=50), nullable=True, comment="Версия спецификации"),
    )
    op.add_column(
        "specs",
        sa.Column(
            "content", sa.JSON(), nullable=True, comment="Содержимое спецификации в JSON формате"
        ),
    )
    op.add_column(
        "specs",
        sa.Column("format", sa.String(length=20), nullable=True, comment="Формат документа"),
    )
    op.add_column(
        "specs",
        sa.Column("language", sa.String(length=10), nullable=True, comment="Язык спецификации"),
    )
    op.add_column(
        "specs",
        sa.Column("status", sa.String(length=50), nullable=True, comment="Статус спецификации"),
    )
    op.add_column(
        "specs",
        sa.Column("generated_by", sa.Integer(), nullable=True, comment="Создана пользователем"),
    )
    op.add_column(
        "specs",
        sa.Column(
            "updated_at", sa.DateTime(), nullable=True, comment="Время последнего обновления"
        ),
    )
    op.create_foreign_key(
        op.f("fk_specs_generated_by_users"), "specs", "users", ["generated_by"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_specs_generated_by_users"), "specs", type_="foreignkey")
    op.drop_column("specs", "updated_at")
    op.drop_column("specs", "generated_by")
    op.drop_column("specs", "status")
    op.drop_column("specs", "language")
    op.drop_column("specs", "format")
    op.drop_column("specs", "content")
    op.drop_column("specs", "version")
    op.drop_column("specs", "description")
    # ### end Alembic commands ###
