"""replace comment filed text on

Revision ID: f82c77bee2f7
Revises: ed81715576d0
Create Date: 2025-06-28 21:42:05.544061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f82c77bee2f7"
down_revision: Union[str, None] = "ed81715576d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("content", sa.Text(), nullable=False))
    op.drop_column("comments", "text")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "comments", sa.Column("text", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.drop_column("comments", "content")
    # ### end Alembic commands ###
