"""

Revision ID: a272f09e9c8b
Revises: ac9aa8bfe450
Create Date: 2025-08-03 00:27:18.341984

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a272f09e9c8b"
down_revision: Union[str, None] = "ac9aa8bfe450"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ENUM types
    companytype = sa.Enum(
        "STARTUP",
        "SMALL_BUSINESS", 
        "MEDIUM_BUSINESS",
        "ENTERPRISE",
        "NON_PROFIT",
        "GOVERNMENT",
        "EDUCATIONAL",
        name="companytype"
    )
    departmenttype = sa.Enum(
        "ENGINEERING",
        "PRODUCT",
        "DESIGN", 
        "QA",
        "DEVOPS",
        "MARKETING",
        "SALES",
        "SUPPORT",
        "HR",
        "FINANCE",
        "OPERATIONS",
        "ADMINISTRATION",
        "CUSTOM",
        name="departmenttype"
    )
    releasestatus = sa.Enum(
        "PLANNED",
        "IN_DEVELOPMENT",
        "TESTING",
        "REVIEW",
        "READY",
        "RELEASED",
        "CANCELLED",
        "HOTFIX", 
        name="releasestatus"
    )
    companytype.create(op.get_bind(), checkfirst=True)
    departmenttype.create(op.get_bind(), checkfirst=True)
    releasestatus.create(op.get_bind(), checkfirst=True)
    
    op.add_column(
        "comments",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
    )
    op.alter_column(
        "comments",
        "content",
        existing_type=sa.TEXT(),
        comment="Содержание комментария",
        existing_nullable=False,
    )
    op.alter_column(
        "comments",
        "requirement_id",
        existing_type=sa.INTEGER(),
        comment="ID требования",
        existing_nullable=False,
    )
    op.alter_column(
        "comments",
        "author_id",
        existing_type=sa.INTEGER(),
        comment="Автор комментария",
        existing_nullable=False,
    )
    op.alter_column(
        "comments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Время создания записи",
        existing_nullable=False,
    )
    op.create_index("ix_comments_author_id", "comments", ["author_id"], unique=False)
    op.create_index("ix_comments_requirement_id", "comments", ["requirement_id"], unique=False)
    op.drop_constraint(
        op.f("fk_comments_requirement_id_requirements"), "comments", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_comments_author_id_users"), "comments", type_="foreignkey")
    op.drop_constraint(op.f("fk_comments_created_by_users"), "comments", type_="foreignkey")
    op.drop_constraint(op.f("fk_comments_updated_by_users"), "comments", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_comments_requirement_id_requirements"),
        "comments",
        "requirements",
        ["requirement_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_comments_author_id_users"),
        "comments",
        "users",
        ["author_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("comments", "updated_by")
    op.drop_column("comments", "created_by")
    op.alter_column(
        "companies",
        "description",
        existing_type=sa.VARCHAR(length=1000),
        comment="Описание компании",
        existing_comment="Краткое описание компании",
        existing_nullable=True,
    )
    op.alter_column(
        "companies",
        "company_type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "STARTUP",
            "SMALL_BUSINESS",
            "MEDIUM_BUSINESS",
            "ENTERPRISE",
            "NON_PROFIT",
            "GOVERNMENT",
            "EDUCATIONAL",
            name="companytype",
        ),
        nullable=False,
        postgresql_using="company_type::companytype",
        comment="Тип компании",
        existing_comment="Дополнительный тип компании",
    )
    op.drop_index(op.f("ix_companies_legal_name"), table_name="companies")
    op.drop_index(op.f("ix_companies_type"), table_name="companies")
    op.drop_constraint(op.f("fk_companies_owner_id_users"), "companies", type_="foreignkey")
    op.drop_column("companies", "legal_name")
    op.drop_column("companies", "trial_ends_at")
    op.drop_column("companies", "type")
    op.drop_column("companies", "industry")
    op.drop_column("companies", "employee_count")
    op.drop_column("companies", "subscription_plan")
    op.drop_column("companies", "founded_year")
    op.drop_column("companies", "settings")
    op.drop_column("companies", "phone")
    op.drop_column("companies", "owner_id")
    op.drop_column("companies", "timezone")
    op.drop_column("companies", "headquarters")
    op.drop_column("companies", "website")
    op.drop_column("companies", "size_category")
    op.drop_column("companies", "email")
    op.drop_column("companies", "company_metadata")
    op.alter_column(
        "departments",
        "name",
        existing_type=sa.VARCHAR(length=200),
        type_=sa.String(length=100),
        existing_comment="Название департамента",
        existing_nullable=False,
    )
    op.alter_column(
        "departments",
        "description",
        existing_type=sa.TEXT(),
        type_=sa.String(length=500),
        existing_comment="Описание департамента",
        existing_nullable=True,
    )
    op.alter_column(
        "departments",
        "type",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            "ENGINEERING",
            "PRODUCT",
            "DESIGN",
            "QA",
            "DEVOPS",
            "MARKETING",
            "SALES",
            "SUPPORT",
            "HR",
            "FINANCE",
            "OPERATIONS",
            "ADMINISTRATION",
            "CUSTOM",
            name="departmenttype",
        ),
        postgresql_using="type::departmenttype",
        existing_comment="Тип департамента",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_departments_head_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_parent_id"), table_name="departments")
    op.drop_index(op.f("ix_departments_slug"), table_name="departments")
    op.create_index("ix_departments_name", "departments", ["name"], unique=False)
    op.drop_constraint(
        op.f("fk_departments_parent_id_departments"), "departments", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_departments_head_id_users"), "departments", type_="foreignkey")
    op.drop_column("departments", "head_id")
    op.drop_column("departments", "location")
    op.drop_column("departments", "cost_center_code")
    op.drop_column("departments", "slug")
    op.drop_column("departments", "team_count")
    op.drop_column("departments", "annual_budget")
    op.drop_column("departments", "parent_id")
    op.drop_column("departments", "phone")
    op.drop_column("departments", "budget_allocated")
    op.drop_column("departments", "auto_assign_projects")
    op.drop_column("departments", "is_billable")
    op.drop_column("departments", "employee_count")
    op.drop_column("departments", "email")
    op.add_column(
        "releases",
        sa.Column(
            "released_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Фактическая дата релиза",
        ),
    )
    op.alter_column(
        "releases",
        "version",
        existing_type=sa.VARCHAR(length=50),
        comment="Версия релиза",
        existing_comment="SemVer format",
        existing_nullable=False,
    )
    op.alter_column(
        "releases",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=200),
        existing_comment="Название релиза",
        existing_nullable=False,
    )
    op.alter_column(
        "releases",
        "description",
        existing_type=sa.TEXT(),
        type_=sa.String(length=1000),
        existing_comment="Описание релиза",
        existing_nullable=True,
    )
    op.alter_column(
        "releases",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            "PLANNED",
            "IN_DEVELOPMENT",
            "TESTING",
            "REVIEW",
            "READY",
            "RELEASED",
            "CANCELLED",
            "HOTFIX",
            name="releasestatus",
        ),
        postgresql_using="status::releasestatus",
        existing_comment="Статус релиза",
        existing_nullable=False,
    )
    op.alter_column(
        "releases",
        "planned_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="Планируемая дата релиза",
        existing_nullable=True,
    )
    op.alter_column(
        "releases",
        "project_id",
        existing_type=sa.INTEGER(),
        comment="ID проекта",
        existing_nullable=False,
    )
    op.alter_column(
        "releases",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Время создания записи",
        existing_nullable=False,
    )
    op.alter_column(
        "releases",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="Время последнего обновления записи",
        existing_nullable=False,
    )
    op.create_index("ix_releases_project_id", "releases", ["project_id"], unique=False)
    op.create_index("ix_releases_status", "releases", ["status"], unique=False)
    op.create_index("ix_releases_version", "releases", ["version"], unique=False)
    op.drop_constraint(op.f("fk_releases_updated_by_users"), "releases", type_="foreignkey")
    op.drop_constraint(op.f("fk_releases_project_id_projects"), "releases", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_releases_based_on_release_id_releases"), "releases", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_releases_created_by_users"), "releases", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_releases_project_id_projects"),
        "releases",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("releases", "build_number")
    op.drop_column("releases", "release_date")
    op.drop_column("releases", "tags")
    op.drop_column("releases", "release_type")
    op.drop_column("releases", "release_notes")
    op.drop_column("releases", "priority")
    op.drop_column("releases", "is_active")
    op.drop_column("releases", "is_draft")
    op.drop_column("releases", "based_on_release_id")
    op.drop_column("releases", "updated_by")
    op.drop_column("releases", "changelog")
    op.drop_column("releases", "repository_tag")
    op.drop_column("releases", "created_by")
    op.drop_column("releases", "is_prerelease")
    op.alter_column(
        "requirements",
        "description",
        existing_type=sa.TEXT(),
        comment="Описание требования",
        existing_comment="Подробное описание требования",
        existing_nullable=True,
    )
    op.alter_column(
        "requirements",
        "project_id",
        existing_type=sa.INTEGER(),
        comment="ID проекта",
        existing_comment="Проект, к которому относится требование",
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_requirements_author_created"), table_name="requirements")
    op.drop_index(op.f("ix_requirements_project_status"), table_name="requirements")
    op.create_index("ix_requirements_author_id", "requirements", ["author_id"], unique=False)
    op.create_index("ix_requirements_project_id", "requirements", ["project_id"], unique=False)
    op.create_index("ix_requirements_status_id", "requirements", ["status_id"], unique=False)
    op.create_index("ix_requirements_type_id", "requirements", ["type_id"], unique=False)
    op.drop_constraint(
        op.f("fk_requirements_parent_requirement_id_requirements"),
        "requirements",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_requirements_release_id_releases"), "requirements", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_requirements_updated_by_users"), "requirements", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_requirements_last_modified_by_users"), "requirements", type_="foreignkey"
    )
    op.drop_constraint(op.f("fk_requirements_spec_id_specs"), "requirements", type_="foreignkey")
    op.drop_constraint(op.f("fk_requirements_created_by_users"), "requirements", type_="foreignkey")
    op.drop_column("requirements", "tags")
    op.drop_column("requirements", "effort_estimate")
    op.drop_column("requirements", "parent_requirement_id")
    op.drop_column("requirements", "deadline")
    op.drop_column("requirements", "release_id")
    op.drop_column("requirements", "spec_id")
    op.drop_column("requirements", "source")
    op.drop_column("requirements", "updated_by")
    op.drop_column("requirements", "complexity")
    op.drop_column("requirements", "progress")
    op.drop_column("requirements", "acceptance_criteria")
    op.drop_column("requirements", "created_by")
    op.drop_column("requirements", "last_modified_by")
    op.drop_column("requirements", "business_value")
    op.alter_column(
        "teams",
        "description",
        existing_type=sa.TEXT(),
        type_=sa.String(length=500),
        existing_comment="Описание команды",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_teams_code_unique"), table_name="teams")
    op.drop_index(op.f("ix_teams_owner_status"), table_name="teams")
    op.drop_index(op.f("ix_teams_status_created"), table_name="teams")
    op.drop_constraint(op.f("uq_teams_code"), "teams", type_="unique")
    op.create_index("ix_teams_is_active", "teams", ["is_active"], unique=False)
    op.create_index("ix_teams_owner_id", "teams", ["owner_id"], unique=False)
    op.drop_constraint(op.f("fk_teams_updated_by_users"), "teams", type_="foreignkey")
    op.drop_constraint(op.f("fk_teams_project_id_projects"), "teams", type_="foreignkey")
    op.drop_constraint(op.f("fk_teams_created_by_users"), "teams", type_="foreignkey")
    op.drop_constraint(op.f("fk_teams_company_id_companies"), "teams", type_="foreignkey")
    op.drop_column("teams", "location")
    op.drop_column("teams", "visibility")
    op.drop_column("teams", "tags")
    op.drop_column("teams", "company_id")
    op.drop_column("teams", "project_id")
    op.drop_column("teams", "team_type")
    op.drop_column("teams", "status")
    op.drop_column("teams", "is_public")
    op.drop_column("teams", "max_members")
    op.drop_column("teams", "updated_by")
    op.drop_column("teams", "created_by")
    op.drop_column("teams", "code")
    op.add_column(
        "users",
        sa.Column("password_hash", sa.String(length=255), nullable=False, comment="Хеш пароля"),
    )
    op.add_column(
        "users",
        sa.Column("name", sa.String(length=100), nullable=False, comment="Имя пользователя"),
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=255),
        comment="Email пользователя",
        existing_comment="Email адрес пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "company_id",
        existing_type=sa.INTEGER(),
        comment="ID компании пользователя",
        existing_comment="Основная компания пользователя (NULL для System Admin, reference-only)",
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_users_auth_provider"), table_name="users")
    op.drop_index(op.f("ix_users_auth_provider_id_unique"), table_name="users")
    op.drop_index(op.f("ix_users_email_unique"), table_name="users")
    op.drop_index(op.f("ix_users_is_email_verified"), table_name="users")
    op.drop_index(op.f("ix_users_last_login_at"), table_name="users")
    op.drop_index(op.f("ix_users_login_attempts"), table_name="users")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_username_unique"), table_name="users")
    op.drop_constraint(op.f("uq_users_auth_provider_id"), "users", type_="unique")
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.drop_constraint(op.f("fk_users_company_id_companies"), "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_users_company_id_companies"),
        "users",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("users", "user_metadata")
    op.drop_column("users", "locked_until")
    op.drop_column("users", "auth_provider")
    op.drop_column("users", "auth_provider_id")
    op.drop_column("users", "terms_accepted_at")
    op.drop_column("users", "username")
    op.drop_column("users", "is_email_verified")
    op.drop_column("users", "preferences")
    op.drop_column("users", "privacy_policy_accepted_at")
    op.drop_column("users", "email_verified_at")
    op.drop_column("users", "last_login_at")
    op.drop_column("users", "status")
    op.drop_column("users", "password_changed_at")
    op.drop_column("users", "login_attempts")
    op.drop_column("users", "hashed_password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "hashed_password",
            sa.VARCHAR(length=128),
            autoincrement=False,
            nullable=False,
            comment="Хэшированный пароль",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "login_attempts",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Количество неудачных попыток входа",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "password_changed_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Дата последней смены пароля",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
            comment="Статус пользователя",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "last_login_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Время последнего входа в систему",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email_verified_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Время подтверждения email",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "privacy_policy_accepted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Дата принятия политики конфиденциальности",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "preferences",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="Пользовательские настройки",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_email_verified",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Подтвержден ли email пользователя",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "username",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="Уникальное имя пользователя",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "terms_accepted_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Дата принятия условий использования",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "auth_provider_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="ID пользователя у внешнего провайдера",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "auth_provider",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
            comment="Провайдер аутентификации",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "locked_until",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Заблокирован до (после множественных неудачных попыток)",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "user_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="Дополнительные метаданные",
        ),
    )
    op.drop_constraint(op.f("fk_users_company_id_companies"), "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_users_company_id_companies"), "users", "companies", ["company_id"], ["id"]
    )
    op.drop_index("ix_users_email", table_name="users")
    op.create_unique_constraint(
        op.f("uq_users_username"), "users", ["username"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("uq_users_auth_provider_id"),
        "users",
        ["auth_provider_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_users_username_unique"), "users", ["username"], unique=True)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(op.f("ix_users_login_attempts"), "users", ["login_attempts"], unique=False)
    op.create_index(op.f("ix_users_last_login_at"), "users", ["last_login_at"], unique=False)
    op.create_index(
        op.f("ix_users_is_email_verified"), "users", ["is_email_verified"], unique=False
    )
    op.create_index(op.f("ix_users_email_unique"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_auth_provider_id_unique"), "users", ["auth_provider_id"], unique=True
    )
    op.create_index(op.f("ix_users_auth_provider"), "users", ["auth_provider"], unique=False)
    op.alter_column(
        "users",
        "company_id",
        existing_type=sa.INTEGER(),
        comment="Основная компания пользователя (NULL для System Admin, reference-only)",
        existing_comment="ID компании пользователя",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=100),
        comment="Email адрес пользователя",
        existing_comment="Email пользователя",
        existing_nullable=False,
    )
    op.drop_column("users", "name")
    op.drop_column("users", "password_hash")
    op.add_column(
        "teams",
        sa.Column(
            "code",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="Уникальный код команды",
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "created_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Кто создал команду",
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "updated_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Кто последний обновил команду",
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "max_members",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Максимальное количество участников",
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "is_public",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Публичная ли команда",
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
            comment="Статус команды",
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "team_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="Тип команды",
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "project_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Основной проект команды",
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "company_id", sa.INTEGER(), autoincrement=False, nullable=True, comment="ID компании"
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "tags",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="Теги команды",
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "visibility",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
            comment="Видимость команды",
        ),
    )
    op.add_column(
        "teams",
        sa.Column(
            "location",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
            comment="Местоположение команды",
        ),
    )
    op.create_foreign_key(
        op.f("fk_teams_company_id_companies"),
        "teams",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_teams_created_by_users"),
        "teams",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_teams_project_id_projects"),
        "teams",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_teams_updated_by_users"),
        "teams",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index("ix_teams_owner_id", table_name="teams")
    op.drop_index("ix_teams_is_active", table_name="teams")
    op.create_unique_constraint(
        op.f("uq_teams_code"), "teams", ["code"], postgresql_nulls_not_distinct=False
    )
    op.create_index(
        op.f("ix_teams_status_created"), "teams", ["status", "created_at"], unique=False
    )
    op.create_index(op.f("ix_teams_owner_status"), "teams", ["owner_id", "status"], unique=False)
    op.create_index(op.f("ix_teams_code_unique"), "teams", ["code"], unique=True)
    op.alter_column(
        "teams",
        "description",
        existing_type=sa.String(length=500),
        type_=sa.TEXT(),
        existing_comment="Описание команды",
        existing_nullable=True,
    )
    op.add_column(
        "requirements",
        sa.Column(
            "business_value",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
            comment="Бизнес-ценность требования",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "last_modified_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Последний редактор требования",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "created_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Кто создал требование",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "acceptance_criteria",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Критерии приемки требования",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "progress",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
            comment="Прогресс выполнения требования (0.0-100.0)",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "complexity",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="Сложность требования",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "updated_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Кто последний обновил требование",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "source",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
            comment="Источник требования",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "spec_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Спецификация, к которой относится требование",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "release_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Релиз, в котором реализуется требование",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "deadline",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment="Срок выполнения требования",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "parent_requirement_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Родительское требование",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "effort_estimate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Оценка трудозатрат (часы)",
        ),
    )
    op.add_column(
        "requirements",
        sa.Column(
            "tags",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="Теги требования",
        ),
    )
    op.create_foreign_key(
        op.f("fk_requirements_created_by_users"),
        "requirements",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_requirements_spec_id_specs"),
        "requirements",
        "specs",
        ["spec_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_requirements_last_modified_by_users"),
        "requirements",
        "users",
        ["last_modified_by"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_requirements_updated_by_users"),
        "requirements",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_requirements_release_id_releases"),
        "requirements",
        "releases",
        ["release_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_requirements_parent_requirement_id_requirements"),
        "requirements",
        "requirements",
        ["parent_requirement_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("ix_requirements_type_id", table_name="requirements")
    op.drop_index("ix_requirements_status_id", table_name="requirements")
    op.drop_index("ix_requirements_project_id", table_name="requirements")
    op.drop_index("ix_requirements_author_id", table_name="requirements")
    op.create_index(
        op.f("ix_requirements_project_status"),
        "requirements",
        ["project_id", "status_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_requirements_author_created"),
        "requirements",
        ["author_id", "created_at"],
        unique=False,
    )
    op.alter_column(
        "requirements",
        "project_id",
        existing_type=sa.INTEGER(),
        comment="Проект, к которому относится требование",
        existing_comment="ID проекта",
        existing_nullable=False,
    )
    op.alter_column(
        "requirements",
        "description",
        existing_type=sa.TEXT(),
        comment="Подробное описание требования",
        existing_comment="Описание требования",
        existing_nullable=True,
    )
    op.add_column(
        "releases",
        sa.Column(
            "is_prerelease", sa.BOOLEAN(), autoincrement=False, nullable=False, comment="Пре-релиз"
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "created_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Кто создал релиз",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "repository_tag",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
            comment="Тег в репозитории",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "changelog", sa.TEXT(), autoincrement=False, nullable=True, comment="Список изменений"
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "updated_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Кто последний обновил релиз",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "based_on_release_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Базовый релиз",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "is_draft",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Черновик ли релиз",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Активен ли релиз",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "priority",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
            comment="Приоритет релиза",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "release_notes",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Заметки к релизу",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "release_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="Тип релиза",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "tags",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="Теги релиза",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "release_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Фактическая дата релиза",
        ),
    )
    op.add_column(
        "releases",
        sa.Column(
            "build_number",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="Номер сборки",
        ),
    )
    op.drop_constraint(op.f("fk_releases_project_id_projects"), "releases", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_releases_created_by_users"),
        "releases",
        "users",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_releases_based_on_release_id_releases"),
        "releases",
        "releases",
        ["based_on_release_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_releases_project_id_projects"), "releases", "projects", ["project_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_releases_updated_by_users"),
        "releases",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index("ix_releases_version", table_name="releases")
    op.drop_index("ix_releases_status", table_name="releases")
    op.drop_index("ix_releases_project_id", table_name="releases")
    op.alter_column(
        "releases",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Время последнего обновления записи",
        existing_nullable=False,
    )
    op.alter_column(
        "releases",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Время создания записи",
        existing_nullable=False,
    )
    op.alter_column(
        "releases",
        "project_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="ID проекта",
        existing_nullable=False,
    )
    op.alter_column(
        "releases",
        "planned_date",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="Планируемая дата релиза",
        existing_nullable=True,
    )
    op.alter_column(
        "releases",
        "status",
        existing_type=sa.Enum(
            "PLANNED",
            "IN_DEVELOPMENT",
            "TESTING",
            "REVIEW",
            "READY",
            "RELEASED",
            "CANCELLED",
            "HOTFIX",
            name="releasestatus",
        ),
        type_=sa.VARCHAR(length=20),
        existing_comment="Статус релиза",
        existing_nullable=False,
    )
    op.alter_column(
        "releases",
        "description",
        existing_type=sa.String(length=1000),
        type_=sa.TEXT(),
        existing_comment="Описание релиза",
        existing_nullable=True,
    )
    op.alter_column(
        "releases",
        "name",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=100),
        existing_comment="Название релиза",
        existing_nullable=False,
    )
    op.alter_column(
        "releases",
        "version",
        existing_type=sa.VARCHAR(length=50),
        comment="SemVer format",
        existing_comment="Версия релиза",
        existing_nullable=False,
    )
    op.drop_column("releases", "released_date")
    op.add_column(
        "departments",
        sa.Column(
            "email",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
            comment="Email департамента",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "employee_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Количество сотрудников",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "is_billable",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Участвует ли в биллинге",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "auto_assign_projects",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Автоматически назначать проекты этого типа",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "budget_allocated",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Выделенный бюджет департамента",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "phone",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
            comment="Телефон департамента",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "parent_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Родительский департамент",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "annual_budget",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
            comment="Годовой бюджет департамента",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "team_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Количество команд",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "slug",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment="URL-friendly идентификатор",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "cost_center_code",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="Код центра затрат",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "location",
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=True,
            comment="Основное местоположение",
        ),
    )
    op.add_column(
        "departments",
        sa.Column(
            "head_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Руководитель департамента",
        ),
    )
    op.create_foreign_key(
        op.f("fk_departments_head_id_users"),
        "departments",
        "users",
        ["head_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_departments_parent_id_departments"),
        "departments",
        "departments",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index("ix_departments_name", table_name="departments")
    op.create_index(op.f("ix_departments_slug"), "departments", ["company_id", "slug"], unique=True)
    op.create_index(op.f("ix_departments_parent_id"), "departments", ["parent_id"], unique=False)
    op.create_index(op.f("ix_departments_head_id"), "departments", ["head_id"], unique=False)
    op.alter_column(
        "departments",
        "type",
        existing_type=sa.Enum(
            "ENGINEERING",
            "PRODUCT",
            "DESIGN",
            "QA",
            "DEVOPS",
            "MARKETING",
            "SALES",
            "SUPPORT",
            "HR",
            "FINANCE",
            "OPERATIONS",
            "ADMINISTRATION",
            "CUSTOM",
            name="departmenttype",
        ),
        type_=sa.VARCHAR(length=50),
        existing_comment="Тип департамента",
        existing_nullable=False,
    )
    op.alter_column(
        "departments",
        "description",
        existing_type=sa.String(length=500),
        type_=sa.TEXT(),
        existing_comment="Описание департамента",
        existing_nullable=True,
    )
    op.alter_column(
        "departments",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=200),
        existing_comment="Название департамента",
        existing_nullable=False,
    )
    op.add_column(
        "companies",
        sa.Column(
            "company_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="Дополнительные метаданные компании",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "email",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="Основной email компании",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "size_category",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="Категория размера (micro, small, medium, large)",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "website",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
            comment="Веб-сайт компании",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "headquarters",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
            comment="Местоположение штаб-квартиры",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "timezone",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="Часовой пояс компании",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "owner_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Владелец компании",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "phone",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=True,
            comment="Основной телефон компании",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "settings",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="Настройки компании",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "founded_year",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Год основания компании",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "subscription_plan",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
            comment="План подписки",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "employee_count",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Количество сотрудников",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "industry",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
            comment="Отрасль",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "type",
            postgresql.ENUM(
                "STARTUP",
                "SMALL_BUSINESS",
                "MEDIUM_BUSINESS",
                "ENTERPRISE",
                "NON_PROFIT",
                "GOVERNMENT",
                "EDUCATIONAL",
                name="companytype",
            ),
            autoincrement=False,
            nullable=False,
            comment="Тип компании",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "trial_ends_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Дата окончания пробного периода",
        ),
    )
    op.add_column(
        "companies",
        sa.Column(
            "legal_name",
            sa.VARCHAR(length=300),
            autoincrement=False,
            nullable=True,
            comment="Юридическое название",
        ),
    )
    op.create_foreign_key(
        op.f("fk_companies_owner_id_users"),
        "companies",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(op.f("ix_companies_type"), "companies", ["type"], unique=False)
    op.create_index(op.f("ix_companies_legal_name"), "companies", ["legal_name"], unique=False)
    op.alter_column(
        "companies",
        "company_type",
        existing_type=sa.Enum(
            "STARTUP",
            "SMALL_BUSINESS",
            "MEDIUM_BUSINESS",
            "ENTERPRISE",
            "NON_PROFIT",
            "GOVERNMENT",
            "EDUCATIONAL",
            name="companytype",
        ),
        type_=sa.VARCHAR(length=50),
        nullable=True,
        comment="Дополнительный тип компании",
        existing_comment="Тип компании",
    )
    op.alter_column(
        "companies",
        "description",
        existing_type=sa.VARCHAR(length=1000),
        comment="Краткое описание компании",
        existing_comment="Описание компании",
        existing_nullable=True,
    )
    op.add_column(
        "comments",
        sa.Column(
            "created_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Кто создал комментарий",
        ),
    )
    op.add_column(
        "comments",
        sa.Column(
            "updated_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Кто последний обновил комментарий",
        ),
    )
    op.drop_constraint(op.f("fk_comments_author_id_users"), "comments", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_comments_requirement_id_requirements"), "comments", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_comments_updated_by_users"),
        "comments",
        "users",
        ["updated_by"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_comments_created_by_users"),
        "comments",
        "users",
        ["created_by"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_comments_author_id_users"), "comments", "users", ["author_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_comments_requirement_id_requirements"),
        "comments",
        "requirements",
        ["requirement_id"],
        ["id"],
    )
    op.drop_index("ix_comments_requirement_id", table_name="comments")
    op.drop_index("ix_comments_author_id", table_name="comments")
    op.alter_column(
        "comments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="Время создания записи",
        existing_nullable=False,
    )
    op.alter_column(
        "comments",
        "author_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Автор комментария",
        existing_nullable=False,
    )
    op.alter_column(
        "comments",
        "requirement_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="ID требования",
        existing_nullable=False,
    )
    op.alter_column(
        "comments",
        "content",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Содержание комментария",
        existing_nullable=False,
    )
    op.drop_column("comments", "updated_at")
    # ### end Alembic commands ###
