"""add_owner_id_to_projects

Revision ID: 4ac2d2b53298
Revises: c8a2e1c8e3d0
Create Date: 2025-06-29 10:29:53.831874

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ac2d2b53298"
down_revision: Union[str, None] = "c8a2e1c8e3d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add column as nullable first
    op.add_column(
        "projects",
        sa.Column("owner_id", sa.Integer(), nullable=True, comment="Владелец проекта"),
    )

    # Step 2: Get the first user (admin) or create a default admin if none exists
    connection = op.get_bind()

    # Check if any users exist
    result = connection.execute(sa.text("SELECT id FROM users ORDER BY id LIMIT 1"))
    first_user = result.fetchone()

    if first_user:
        default_owner_id = first_user[0]
    else:
        # Create a default admin user if no users exist
        from datetime import datetime, UTC
        import hashlib

        # Hash a default password
        default_password = "admin123"
        hashed_password = hashlib.sha256(default_password.encode()).hexdigest()

        # Insert default admin user
        connection.execute(
            sa.text(
                """
            INSERT INTO users (username, email, hashed_password, name, role, is_active, is_superuser, 
                              email_verified, created_at, updated_at)
            VALUES ('admin', 'admin@example.com', :password, 'Default Admin', 'admin', true, true, true, 
                    :now, :now)
        """
            ),
            {
                "password": hashed_password,
                "now": datetime.now(UTC).replace(tzinfo=None),
            },
        )

        # Get the newly created user ID
        result = connection.execute(
            sa.text("SELECT id FROM users WHERE username = 'admin'")
        )
        default_owner_id = result.fetchone()[0]

    # Step 3: Update all existing projects to have the default owner
    connection.execute(
        sa.text(
            """
        UPDATE projects 
        SET owner_id = :owner_id 
        WHERE owner_id IS NULL
    """
        ),
        {"owner_id": default_owner_id},
    )

    # Step 4: Make the column NOT NULL
    op.alter_column("projects", "owner_id", nullable=False)

    # Step 5: Add foreign key constraint
    op.create_foreign_key(
        op.f("fk_projects_owner_id_users"),
        "projects",
        "users",
        ["owner_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_projects_owner_id_users"), "projects", type_="foreignkey"
    )
    op.drop_column("projects", "owner_id")
    # ### end Alembic commands ###
