"""add ProjectStatus

Revision ID: c8a2e1c8e3d0
Revises: f82c77bee2f7
Create Date: 2025-06-29 01:30:15.071729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8a2e1c8e3d0"
down_revision: Union[str, None] = "f82c77bee2f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "status",
        existing_type=sa.VARCHAR(length=50),
        comment="Статус проекта",
        existing_comment="Статус проекта (active, completed, archived)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "status",
        existing_type=sa.VARCHAR(length=50),
        comment="Статус проекта (active, completed, archived)",
        existing_comment="Статус проекта",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
