#!/bin/bash
# DNS Configuration Script for Requify Platform (Linux/macOS)
# Configures local DNS resolution for all Requify services

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HOSTS_FILE="/etc/hosts"
DNS_SERVER="${DNS_SERVER:-127.0.0.1}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Output functions
log_success() { echo -e "${GREEN}✅ $1${NC}"; }
log_error() { echo -e "${RED}❌ $1${NC}"; }
log_info() { echo -e "${CYAN}ℹ️  $1${NC}"; }
log_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
log_header() { echo -e "${BLUE}$1${NC}"; }

# Requify service domains and their container ports
declare -A REQUIFY_SERVICES=(
    # Main domains
    ["requify.local"]="80:nginx:Main Application"
    ["api.requify.local"]="8000:backend:Backend API"
    ["cdn.requify.local"]="9000:minio:CDN/Object Storage"
    ["admin.requify.local"]="9001:minio:MinIO Admin Console"
    
    # Development tools
    ["db.requify.local"]="8080:adminer:Database Admin (Adminer)"
    ["mail.requify.local"]="8025:mailhog:Mail Testing (MailHog)"
    ["docs.requify.local"]="80:nginx:Documentation"
    
    # Direct service access
    ["postgres.requify.local"]="5432:postgres:PostgreSQL Database"
    ["redis.requify.local"]="6379:redis:Redis Cache"
    ["frontend.requify.local"]="3000:frontend:Frontend Dev Server"
)

show_help() {
    cat << EOF

${BLUE}Requify DNS Configuration Script${NC}
================================

${GREEN}USAGE:${NC}
  $0 [ACTION] [OPTIONS]

${GREEN}ACTIONS:${NC}
  configure         Configure DNS entries (default)
  remove           Remove all Requify DNS entries
  status           Show current configuration status
  test             Test DNS resolution
  test-connections Test HTTP connections to services
  help             Show this help message

${GREEN}OPTIONS:${NC}
  --dns-server <IP>    DNS server to use (default: 127.0.0.1)
  --show-status        Show status after configuration
  --test-connections   Test connections after configuration
  --dry-run           Show what would be done without making changes

${GREEN}EXAMPLES:${NC}
  $0                              # Configure with defaults
  $0 --show-status                # Configure and show status
  $0 --test-connections           # Configure and test connections
  $0 remove                       # Remove DNS entries
  $0 status                       # Show current status
  $0 test                         # Test DNS resolution
  $0 test-connections             # Test service connections

${GREEN}DOMAINS CONFIGURED:${NC}
EOF

    for domain in $(printf '%s\n' "${!REQUIFY_SERVICES[@]}" | sort); do
        IFS=':' read -r port service description <<< "${REQUIFY_SERVICES[$domain]}"
        echo "  $domain -> $description"
    done
    echo
}

check_privileges() {
    if [[ $EUID -ne 0 ]] && [[ "$1" != "status" ]] && [[ "$1" != "test"* ]] && [[ "$1" != "help" ]]; then
        log_error "This script requires root privileges to modify $HOSTS_FILE"
        log_info "Please run with sudo: sudo $0 $*"
        exit 1
    fi
}

backup_hosts_file() {
    local backup_file="$HOSTS_FILE.backup.$(date '+%Y%m%d-%H%M%S')"
    
    if cp "$HOSTS_FILE" "$backup_file" 2>/dev/null; then
        log_info "Hosts file backed up to: $backup_file"
        echo "$backup_file"
    else
        log_error "Failed to backup hosts file"
        return 1
    fi
}

get_current_hosts_entries() {
    if [[ -f "$HOSTS_FILE" ]]; then
        grep -E "^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+.*\.requify\.local" "$HOSTS_FILE" || true
    fi
}

add_hosts_entries() {
    local ip_address="$1"
    local backup_file
    
    log_info "Adding Requify DNS entries to hosts file..."
    
    # Create backup
    if ! backup_file=$(backup_hosts_file); then
        return 1
    fi
    
    # Remove existing Requify entries
    if [[ -f "$HOSTS_FILE" ]]; then
        grep -v "\.requify\.local" "$HOSTS_FILE" > "$HOSTS_FILE.tmp" || true
        grep -v "=== Requify Platform DNS Configuration ===" "$HOSTS_FILE.tmp" > "$HOSTS_FILE.tmp2" || true
        grep -v "=== End Requify Configuration ===" "$HOSTS_FILE.tmp2" > "$HOSTS_FILE.tmp3" || true
        mv "$HOSTS_FILE.tmp3" "$HOSTS_FILE.tmp"
        rm -f "$HOSTS_FILE.tmp2" "$HOSTS_FILE.tmp3" 2>/dev/null || true
    else
        touch "$HOSTS_FILE.tmp"
    fi
    
    # Add Requify entries
    cat >> "$HOSTS_FILE.tmp" << EOF

# === Requify Platform DNS Configuration ===
# Generated by configure-dns.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Docker containers: $(docker ps --format '{{.Names}}' 2>/dev/null | tr '\n' ',' | sed 's/,$//' || echo "N/A")
EOF
    
    # Add all service entries (sorted)
    for domain in $(printf '%s\n' "${!REQUIFY_SERVICES[@]}" | sort); do
        IFS=':' read -r port service description <<< "${REQUIFY_SERVICES[$domain]}"
        echo "$ip_address	$domain	# $description - Port $port" >> "$HOSTS_FILE.tmp"
    done
    
    cat >> "$HOSTS_FILE.tmp" << EOF
# === End Requify Configuration ===

EOF
    
    # Replace hosts file atomically
    if mv "$HOSTS_FILE.tmp" "$HOSTS_FILE"; then
        log_success "DNS entries configured successfully"
        log_info "Added $(printf '%s\n' "${!REQUIFY_SERVICES[@]}" | wc -l) Requify domains to hosts file"
        return 0
    else
        log_error "Failed to update hosts file"
        # Restore backup if possible
        if [[ -f "$backup_file" ]]; then
            cp "$backup_file" "$HOSTS_FILE" 2>/dev/null || true
            log_info "Hosts file restored from backup"
        fi
        return 1
    fi
}

remove_hosts_entries() {
    local backup_file
    
    log_info "Removing Requify DNS entries from hosts file..."
    
    # Create backup
    if ! backup_file=$(backup_hosts_file); then
        return 1
    fi
    
    # Remove Requify entries
    if [[ -f "$HOSTS_FILE" ]]; then
        grep -v "\.requify\.local" "$HOSTS_FILE" > "$HOSTS_FILE.tmp" || true
        grep -v "=== Requify Platform DNS Configuration ===" "$HOSTS_FILE.tmp" > "$HOSTS_FILE.tmp2" || true
        grep -v "=== End Requify Configuration ===" "$HOSTS_FILE.tmp2" > "$HOSTS_FILE.tmp3" || true
        mv "$HOSTS_FILE.tmp3" "$HOSTS_FILE"
        rm -f "$HOSTS_FILE.tmp" "$HOSTS_FILE.tmp2" 2>/dev/null || true
        
        log_success "Requify DNS entries removed from hosts file"
        return 0
    else
        log_warning "Hosts file not found"
        return 1
    fi
}

test_dns_resolution() {
    log_info "Testing DNS resolution for Requify domains..."
    echo
    
    local success_count=0
    local total_count=0
    
    printf "%-25s %-15s %-10s %s\n" "Domain" "IP Address" "Port" "Description"
    echo "================================================================================"
    
    for domain in $(printf '%s\n' "${!REQUIFY_SERVICES[@]}" | sort); do
        IFS=':' read -r port service description <<< "${REQUIFY_SERVICES[$domain]}"
        total_count=$((total_count + 1))
        
        if ip=$(dig +short "$domain" 2>/dev/null | head -n1); then
            if [[ -n "$ip" ]]; then
                printf "${GREEN}%-25s %-15s %-10s %s${NC}\n" "$domain" "$ip" "Port $port" "$description"
                success_count=$((success_count + 1))
            else
                printf "${RED}%-25s %-15s %-10s %s${NC}\n" "$domain" "No resolution" "Port $port" "$description"
            fi
        else
            printf "${RED}%-25s %-15s %-10s %s${NC}\n" "$domain" "Error" "Port $port" "$description"
        fi
    done
    
    echo "================================================================================"
    echo
    
    if [[ $success_count -eq $total_count ]]; then
        log_success "All $total_count domains resolved successfully"
    else
        log_warning "$success_count/$total_count domains resolved successfully"
    fi
}

test_service_connections() {
    log_info "Testing HTTP connections to Requify services..."
    echo
    
    local -A http_services=(
        ["http://requify.local"]="Main Application"
        ["http://api.requify.local/health"]="Backend API Health"
        ["http://frontend.requify.local"]="Frontend Dev Server"
        ["http://cdn.requify.local/minio/health/live"]="MinIO Health"
        ["http://admin.requify.local"]="MinIO Console"
        ["http://db.requify.local"]="Adminer"
        ["http://mail.requify.local"]="MailHog"
    )
    
    local success_count=0
    local total_count=0
    
    printf "%-45s %-15s %s\n" "URL" "Status Code" "Description"
    echo "=========================================================================================="
    
    for url in $(printf '%s\n' "${!http_services[@]}" | sort); do
        description="${http_services[$url]}"
        total_count=$((total_count + 1))
        
        if status_code=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 "$url" 2>/dev/null); then
            if [[ "$status_code" =~ ^[23] ]]; then
                printf "${GREEN}%-45s %-15s %s${NC}\n" "$url" "[$status_code]" "$description"
                success_count=$((success_count + 1))
            else
                printf "${YELLOW}%-45s %-15s %s${NC}\n" "$url" "[$status_code]" "$description"
            fi
        else
            printf "${RED}%-45s %-15s %s${NC}\n" "$url" "[Error]" "$description"
        fi
    done
    
    echo "=========================================================================================="
    echo
    
    if [[ $success_count -eq $total_count ]]; then
        log_success "All $total_count services are accessible"
    else
        log_warning "$success_count/$total_count services are accessible"
    fi
}

show_current_status() {
    echo
    log_header "=== Requify DNS Configuration Status ==="
    echo
    
    # Check Docker containers
    log_info "Checking Docker containers..."
    if docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" 2>/dev/null | tail -n +2; then
        echo
        log_success "Docker containers are running"
    else
        log_warning "Docker not available or containers not running"
    fi
    
    echo
    
    # Check current hosts entries
    log_info "Current hosts file entries for Requify:"
    if current_entries=$(get_current_hosts_entries); then
        if [[ -n "$current_entries" ]]; then
            echo "$current_entries" | while read -r line; do
                echo "  $line"
            done
            entry_count=$(echo "$current_entries" | wc -l)
            log_success "Found $entry_count Requify DNS entries"
        else
            log_warning "No Requify DNS entries found in hosts file"
        fi
    else
        log_warning "No Requify DNS entries found in hosts file"
    fi
    
    echo
    
    # Show all available services
    log_info "Available Requify services:"
    echo
    printf "%-25s %-10s %-20s %s\n" "Domain" "Port" "Service" "Description"
    echo "--------------------------------------------------------------------------------"
    
    for domain in $(printf '%s\n' "${!REQUIFY_SERVICES[@]}" | sort); do
        IFS=':' read -r port service description <<< "${REQUIFY_SERVICES[$domain]}"
        printf "%-25s %-10s %-20s %s\n" "$domain" "$port" "$service" "$description"
    done
}

# Parse command line arguments
ACTION="configure"
SHOW_STATUS=false
TEST_CONNECTIONS=false
DRY_RUN=false

while [[ $# -gt 0 ]]; do
    case $1 in
        configure|remove|status|test|test-connections|help)
            ACTION="$1"
            shift
            ;;
        --dns-server)
            DNS_SERVER="$2"
            shift 2
            ;;
        --show-status)
            SHOW_STATUS=true
            shift
            ;;
        --test-connections)
            TEST_CONNECTIONS=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        *)
            log_error "Unknown option: $1"
            show_help
            exit 1
            ;;
    esac
done

# Main execution
echo
log_header "🚀 Requify Platform DNS Configurator"
log_header "====================================="
echo

case "$ACTION" in
    configure)
        check_privileges "$ACTION"
        
        if [[ "$DRY_RUN" == "true" ]]; then
            log_info "DRY RUN: Would configure DNS entries for Requify platform..."
            log_info "Would add $(printf '%s\n' "${!REQUIFY_SERVICES[@]}" | wc -l) domains pointing to $DNS_SERVER"
            echo
            for domain in $(printf '%s\n' "${!REQUIFY_SERVICES[@]}" | sort); do
                IFS=':' read -r port service description <<< "${REQUIFY_SERVICES[$domain]}"
                echo "  $DNS_SERVER	$domain	# $description - Port $port"
            done
        else
            log_info "Configuring DNS entries for Requify platform..."
            
            if add_hosts_entries "$DNS_SERVER"; then
                if [[ "$SHOW_STATUS" == "true" ]]; then
                    show_current_status
                fi
                
                if [[ "$TEST_CONNECTIONS" == "true" ]]; then
                    test_service_connections
                fi
            fi
        fi
        ;;
        
    remove)
        check_privileges "$ACTION"
        
        if [[ "$DRY_RUN" == "true" ]]; then
            log_info "DRY RUN: Would remove Requify DNS entries..."
            current_entries=$(get_current_hosts_entries)
            if [[ -n "$current_entries" ]]; then
                echo "Would remove:"
                echo "$current_entries" | sed 's/^/  /'
            else
                log_info "No entries to remove"
            fi
        else
            log_info "Removing Requify DNS entries..."
            remove_hosts_entries
        fi
        ;;
        
    status)
        show_current_status
        ;;
        
    test)
        test_dns_resolution
        ;;
        
    test-connections)
        test_service_connections
        ;;
        
    help)
        show_help
        ;;
        
    *)
        log_error "Unknown action: $ACTION"
        log_info "Use 'help' action to see available options"
        show_help
        exit 1
        ;;
esac

echo
log_info "DNS configuration script completed"
echo